/**
 * Copyright (C) 2024-2025 Scott Velez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.using Microsoft.CodeAnalysis;
**/

/*
 * This file is used by the code generation tooling to generate the TelemetryData structure with strongly typed properties.
 * It is NOT meant to be used directly.
 *
**/

using System.Collections.Generic;

namespace SVappsLAB.iRacingTelemetrySDK
{
    public record struct VarItem(string Name, int Type, int Length, bool IsTimeValue, string Desc, string Units);
    public class iRacingVars
    {
        // a dictionary of all known variables from the iRacing SDK - both live sessions and offline ibt files
        // this data is used by the code generation to generate typed variables for your code.
        public Dictionary<TelemetryVar, VarItem> Vars = new()
        {
            { TelemetryVar.AirDensity, new VarItem("AirDensity", 4, 1, false, "Density of air at start/finish line", "kg/m^3") },
            { TelemetryVar.AirPressure, new VarItem("AirPressure", 4, 1, false, "Pressure of air at start/finish line", "Pa") },
            { TelemetryVar.AirTemp, new VarItem("AirTemp", 4, 1, false, "Temperature of air at start/finish line", "C") },
            { TelemetryVar.Alt, new VarItem("Alt", 4, 1, false, "Altitude in meters", "m") },
            { TelemetryVar.Brake, new VarItem("Brake", 4, 1, false, "0=brake released to 1=max pedal force", "%") },
            { TelemetryVar.BrakeABSactive, new VarItem("BrakeABSactive", 1, 1, false, "true if abs is currently reducing brake force pressure", "") },
            { TelemetryVar.BrakeABScutPct, new VarItem("BrakeABScutPct", 4, 1, false, "Percent of brake force reduction caused by ABS system", "%") },
            { TelemetryVar.BrakeRaw, new VarItem("BrakeRaw", 4, 1, false, "Raw brake input 0=brake released to 1=max pedal force", "%") },
            { TelemetryVar.CamCameraNumber, new VarItem("CamCameraNumber", 2, 1, false, "Active camera number", "") },
            { TelemetryVar.CamCameraState, new VarItem("CamCameraState", 3, 1, false, "State of camera system", "CameraState") },
            { TelemetryVar.CamCarIdx, new VarItem("CamCarIdx", 2, 1, false, "Active camera's focus car index", "") },
            { TelemetryVar.CamGroupNumber, new VarItem("CamGroupNumber", 2, 1, false, "Active camera group number", "") },
            { TelemetryVar.CarDistAhead, new VarItem("CarDistAhead", 4, 1, false, "Distance to first car in front of player in meters", "m") },
            { TelemetryVar.CarDistBehind, new VarItem("CarDistBehind", 4, 1, false, "Distance to first car behind player in meters", "m") },
            { TelemetryVar.CarIdxBestLapNum, new VarItem("CarIdxBestLapNum", 2, 64, false, "Cars best lap number", "") },
            { TelemetryVar.CarIdxBestLapTime, new VarItem("CarIdxBestLapTime", 4, 64, false, "Cars best lap time", "s") },
            { TelemetryVar.CarIdxClass, new VarItem("CarIdxClass", 2, 64, false, "Cars class id by car index", "") },
            { TelemetryVar.CarIdxClassPosition, new VarItem("CarIdxClassPosition", 2, 64, false, "Cars class position in race by car index", "") },
            { TelemetryVar.CarIdxEstTime, new VarItem("CarIdxEstTime", 4, 64, false, "Estimated time to reach current location on track", "s") },
            { TelemetryVar.CarIdxF2Time, new VarItem("CarIdxF2Time", 4, 64, false, "Race time behind leader or fastest lap time otherwise", "s") },
            { TelemetryVar.CarIdxFastRepairsUsed, new VarItem("CarIdxFastRepairsUsed", 2, 64, false, "How many fast repairs each car has used", "") },
            { TelemetryVar.CarIdxGear, new VarItem("CarIdxGear", 2, 64, false, "-1=reverse  0=neutral  1..n=current gear by car index", "") },
            { TelemetryVar.CarIdxLap, new VarItem("CarIdxLap", 2, 64, false, "Laps started by car index", "") },
            { TelemetryVar.CarIdxLapCompleted, new VarItem("CarIdxLapCompleted", 2, 64, false, "Laps completed by car index", "") },
            { TelemetryVar.CarIdxLapDistPct, new VarItem("CarIdxLapDistPct", 4, 64, false, "Percentage distance around lap by car index", "%") },
            { TelemetryVar.CarIdxLastLapTime, new VarItem("CarIdxLastLapTime", 4, 64, false, "Cars last lap time", "s") },
            { TelemetryVar.CarIdxOnPitRoad, new VarItem("CarIdxOnPitRoad", 1, 64, false, "On pit road between the cones by car index", "") },
            { TelemetryVar.CarIdxP2P_Count, new VarItem("CarIdxP2P_Count", 2, 64, false, "Push2Pass count of usage (or remaining in Race)", "") },
            { TelemetryVar.CarIdxP2P_Status, new VarItem("CarIdxP2P_Status", 1, 64, false, "Push2Pass active or not", "") },
            { TelemetryVar.CarIdxPaceFlags, new VarItem("CarIdxPaceFlags", 3, 64, false, "Pacing status flags for each car", "PaceFlags") },
            { TelemetryVar.CarIdxPaceLine, new VarItem("CarIdxPaceLine", 2, 64, false, "What line cars are pacing in  or -1 if not pacing", "") },
            { TelemetryVar.CarIdxPaceRow, new VarItem("CarIdxPaceRow", 2, 64, false, "What row cars are pacing in  or -1 if not pacing", "") },
            { TelemetryVar.CarIdxPosition, new VarItem("CarIdxPosition", 2, 64, false, "Cars position in race by car index", "") },
            { TelemetryVar.CarIdxQualTireCompound, new VarItem("CarIdxQualTireCompound", 2, 64, false, "Cars Qual tire compound", "") },
            { TelemetryVar.CarIdxQualTireCompoundLocked, new VarItem("CarIdxQualTireCompoundLocked", 1, 64, false, "Cars Qual tire compound is locked-in", "") },
            { TelemetryVar.CarIdxRPM, new VarItem("CarIdxRPM", 4, 64, false, "Engine rpm by car index", "revs/min") },
            { TelemetryVar.CarIdxSessionFlags, new VarItem("CarIdxSessionFlags", 3, 64, false, "Session flags for each player", "SessionFlags") },
            { TelemetryVar.CarIdxSteer, new VarItem("CarIdxSteer", 4, 64, false, "Steering wheel angle by car index", "rad") },
            { TelemetryVar.CarIdxTireCompound, new VarItem("CarIdxTireCompound", 2, 64, false, "Cars current tire compound", "") },
            { TelemetryVar.CarIdxTrackSurface, new VarItem("CarIdxTrackSurface", 2, 64, false, "Track surface type by car index", "TrackLocation") },
            { TelemetryVar.CarIdxTrackSurfaceMaterial, new VarItem("CarIdxTrackSurfaceMaterial", 2, 64, false, "Track surface material type by car index", "TrackSurface") },
            { TelemetryVar.CarLeftRight, new VarItem("CarLeftRight", 2, 1, false, "Notify if car is to the left or right of driver", "CarLeftRight") },
            { TelemetryVar.CFshockDefl, new VarItem("CFshockDefl", 4, 1, false, "CF shock deflection", "m") },
            { TelemetryVar.CFshockDefl_ST, new VarItem("CFshockDefl_ST", 4, 6, true, "CF shock deflection at 360 Hz", "m") },
            { TelemetryVar.CFshockVel, new VarItem("CFshockVel", 4, 1, false, "CF shock velocity", "m/s") },
            { TelemetryVar.CFshockVel_ST, new VarItem("CFshockVel_ST", 4, 6, true, "CF shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.ChanAvgLatency, new VarItem("ChanAvgLatency", 4, 1, false, "Communications average latency", "s") },
            { TelemetryVar.ChanClockSkew, new VarItem("ChanClockSkew", 4, 1, false, "Communications server clock skew", "s") },
            { TelemetryVar.ChanLatency, new VarItem("ChanLatency", 4, 1, false, "Communications latency", "s") },
            { TelemetryVar.ChanPartnerQuality, new VarItem("ChanPartnerQuality", 4, 1, false, "Partner communications quality", "%") },
            { TelemetryVar.ChanQuality, new VarItem("ChanQuality", 4, 1, false, "Communications quality", "%") },
            { TelemetryVar.Clutch, new VarItem("Clutch", 4, 1, false, "0=disengaged to 1=fully engaged", "%") },
            { TelemetryVar.ClutchRaw, new VarItem("ClutchRaw", 4, 1, false, "Raw clutch input 0=disengaged to 1=fully engaged", "%") },
            { TelemetryVar.CpuUsageBG, new VarItem("CpuUsageBG", 4, 1, false, "Percent of available tim bg thread took with a 1 sec avg", "%") },
            { TelemetryVar.CpuUsageFG, new VarItem("CpuUsageFG", 4, 1, false, "Percent of available tim fg thread took with a 1 sec avg", "%") },
            { TelemetryVar.CRshockDefl, new VarItem("CRshockDefl", 4, 1, false, "CR shock deflection", "m") },
            { TelemetryVar.CRshockDefl_ST, new VarItem("CRshockDefl_ST", 4, 6, true, "CR shock deflection at 360 Hz", "m") },
            { TelemetryVar.CRshockVel, new VarItem("CRshockVel", 4, 1, false, "CR shock velocity", "m/s") },
            { TelemetryVar.CRshockVel_ST, new VarItem("CRshockVel_ST", 4, 6, true, "CR shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.dcABS, new VarItem("dcABS", 4, 1, false, "In car abs adjustment", "") },
            { TelemetryVar.dcAntiRollFront, new VarItem("dcAntiRollFront", 4, 1, false, "In car front anti roll bar adjustment", "") },
            { TelemetryVar.dcAntiRollRear, new VarItem("dcAntiRollRear", 4, 1, false, "In car rear anti roll bar adjustment", "") },
            { TelemetryVar.dcBrakeBias, new VarItem("dcBrakeBias", 4, 1, false, "In car brake bias adjustment", "") },
            { TelemetryVar.dcDashPage, new VarItem("dcDashPage", 4, 1, false, "In car dash display page adjustment", "") },
            { TelemetryVar.DCDriversSoFar, new VarItem("DCDriversSoFar", 2, 1, false, "Number of team drivers who have run a stint", "") },
            { TelemetryVar.dcFuelMixture, new VarItem("dcFuelMixture", 4, 1, false, "In car fuel mixture adjustment", "") },
            { TelemetryVar.dcHeadlightFlash, new VarItem("dcHeadlightFlash", 1, 1, false, "In car headlight flash control active", "") },
            { TelemetryVar.DCLapStatus, new VarItem("DCLapStatus", 2, 1, false, "Status of driver change lap requirements", "") },
            { TelemetryVar.dcLaunchRPM, new VarItem("dcLaunchRPM", 4, 1, false, "In car launch rpm adjustment", "") },
            { TelemetryVar.dcPitSpeedLimiterToggle, new VarItem("dcPitSpeedLimiterToggle", 1, 1, false, "In car traction control active", "") },
            { TelemetryVar.dcPushToPass, new VarItem("dcPushToPass", 1, 1, false, "In car trigger push to pass", "") },
            { TelemetryVar.dcRFBrakeAttachedToggle, new VarItem("dcRFBrakeAttachedToggle", 1, 1, false, "In car Right Front Brake attached(1) or detached(0)", "") },
            { TelemetryVar.dcStarter, new VarItem("dcStarter", 1, 1, false, "In car trigger car starter", "") },
            { TelemetryVar.dcTearOffVisor, new VarItem("dcTearOffVisor", 1, 1, false, "In car tear off visor film", "") },
            { TelemetryVar.dcThrottleShape, new VarItem("dcThrottleShape", 4, 1, false, "In car throttle shape adjustment", "") },
            { TelemetryVar.dcToggleWindshieldWipers, new VarItem("dcToggleWindshieldWipers", 1, 1, false, "In car turn wipers on or off", "") },
            { TelemetryVar.dcTractionControl, new VarItem("dcTractionControl", 4, 1, false, "In car traction control adjustment", "") },
            { TelemetryVar.dcTriggerWindshieldWipers, new VarItem("dcTriggerWindshieldWipers", 1, 1, false, "In car momentarily turn on wipers", "") },
            { TelemetryVar.dcWeightJackerRight, new VarItem("dcWeightJackerRight", 4, 1, false, "In car right wedge/weight jacker adjustment", "") },
            { TelemetryVar.DisplayUnits, new VarItem("DisplayUnits", 2, 1, false, "Default units for the user interface 0 = english 1 = metric", "") },
            { TelemetryVar.dpFastRepair, new VarItem("dpFastRepair", 4, 1, false, "Pitstop fast repair set", "") },
            { TelemetryVar.dpFuelAddKg, new VarItem("dpFuelAddKg", 4, 1, false, "Pitstop fuel add amount", "kg") },
            { TelemetryVar.dpFuelAutoFillActive, new VarItem("dpFuelAutoFillActive", 4, 1, false, "Pitstop auto fill fuel next stop flag", "") },
            { TelemetryVar.dpFuelAutoFillEnabled, new VarItem("dpFuelAutoFillEnabled", 4, 1, false, "Pitstop auto fill fuel system enabled", "") },
            { TelemetryVar.dpFuelFill, new VarItem("dpFuelFill", 4, 1, false, "Pitstop fuel fill flag", "") },
            { TelemetryVar.dpLFTireChange, new VarItem("dpLFTireChange", 4, 1, false, "Pitstop lf tire change request", "") },
            { TelemetryVar.dpLFTireColdPress, new VarItem("dpLFTireColdPress", 4, 1, false, "Pitstop lf tire cold pressure adjustment", "Pa") },
            { TelemetryVar.dpLRTireChange, new VarItem("dpLRTireChange", 4, 1, false, "Pitstop lr tire change request", "") },
            { TelemetryVar.dpLRTireColdPress, new VarItem("dpLRTireColdPress", 4, 1, false, "Pitstop lr tire cold pressure adjustment", "Pa") },
            { TelemetryVar.dpLTireChange, new VarItem("dpLTireChange", 4, 1, false, "Pitstop left tire change request", "") },
            { TelemetryVar.dpRFTireChange, new VarItem("dpRFTireChange", 4, 1, false, "Pitstop rf tire change request", "") },
            { TelemetryVar.dpRFTireColdPress, new VarItem("dpRFTireColdPress", 4, 1, false, "Pitstop rf cold tire pressure adjustment", "Pa") },
            { TelemetryVar.dpRRTireChange, new VarItem("dpRRTireChange", 4, 1, false, "Pitstop rr tire change request", "") },
            { TelemetryVar.dpRRTireColdPress, new VarItem("dpRRTireColdPress", 4, 1, false, "Pitstop rr cold tire pressure adjustment", "Pa") },
            { TelemetryVar.dpRTireChange, new VarItem("dpRTireChange", 4, 1, false, "Pitstop right tire change request", "") },
            { TelemetryVar.dpTireChange, new VarItem("dpTireChange", 4, 1, false, "Pitstop all tire change request", "") },
            { TelemetryVar.dpWindshieldTearoff, new VarItem("dpWindshieldTearoff", 4, 1, false, "Pitstop windshield tearoff", "") },
            { TelemetryVar.dpWingFront, new VarItem("dpWingFront", 4, 1, false, "Pitstop front wing adjustment", "") },
            { TelemetryVar.dpWingRear, new VarItem("dpWingRear", 4, 1, false, "Pitstop rear wing adjustment", "") },
            { TelemetryVar.DriverMarker, new VarItem("DriverMarker", 1, 1, false, "Driver activated flag", "") },
            { TelemetryVar.Engine0_RPM, new VarItem("Engine0_RPM", 4, 1, false, "Engine0Engine rpm", "revs/min") },
            { TelemetryVar.EngineWarnings, new VarItem("EngineWarnings", 3, 1, false, "Bitfield for warning lights", "EngineWarnings") },
            { TelemetryVar.EnterExitReset, new VarItem("EnterExitReset", 2, 1, false, "Indicate action the reset key will take 0 enter 1 exit 2 reset", "") },
            { TelemetryVar.FastRepairAvailable, new VarItem("FastRepairAvailable", 2, 1, false, "How many fast repairs left  255 is unlimited", "") },
            { TelemetryVar.FastRepairUsed, new VarItem("FastRepairUsed", 2, 1, false, "How many fast repairs used so far", "") },
            { TelemetryVar.FogLevel, new VarItem("FogLevel", 4, 1, false, "Fog level at start/finish line", "%") },
            { TelemetryVar.FrameRate, new VarItem("FrameRate", 4, 1, false, "Average frames per second", "fps") },
            { TelemetryVar.FrontTireSetsAvailable, new VarItem("FrontTireSetsAvailable", 2, 1, false, "How many front tire sets are remaining  255 is unlimited", "") },
            { TelemetryVar.FrontTireSetsUsed, new VarItem("FrontTireSetsUsed", 2, 1, false, "How many front tire sets used so far", "") },
            { TelemetryVar.FuelLevel, new VarItem("FuelLevel", 4, 1, false, "Liters of fuel remaining", "l") },
            { TelemetryVar.FuelLevelPct, new VarItem("FuelLevelPct", 4, 1, false, "Percent fuel remaining", "%") },
            { TelemetryVar.FuelPress, new VarItem("FuelPress", 4, 1, false, "Engine fuel pressure", "bar") },
            { TelemetryVar.FuelUsePerHour, new VarItem("FuelUsePerHour", 4, 1, false, "Engine fuel used instantaneous", "kg/h") },
            { TelemetryVar.Gear, new VarItem("Gear", 2, 1, false, "-1=reverse  0=neutral  1..n=current gear", "") },
            { TelemetryVar.GpuUsage, new VarItem("GpuUsage", 4, 1, false, "Percent of available tim gpu took with a 1 sec avg", "%") },
            { TelemetryVar.HandbrakeRaw, new VarItem("HandbrakeRaw", 4, 1, false, "Raw handbrake input 0=handbrake released to 1=max force", "%") },
            { TelemetryVar.IsDiskLoggingActive, new VarItem("IsDiskLoggingActive", 1, 1, false, "0=disk based telemetry file not being written  1=being written", "") },
            { TelemetryVar.IsDiskLoggingEnabled, new VarItem("IsDiskLoggingEnabled", 1, 1, false, "0=disk based telemetry turned off  1=turned on", "") },
            { TelemetryVar.IsGarageVisible, new VarItem("IsGarageVisible", 1, 1, false, "1=Garage screen is visible", "") },
            { TelemetryVar.IsInGarage, new VarItem("IsInGarage", 1, 1, false, "1=Car in garage physics running", "") },
            { TelemetryVar.IsOnTrack, new VarItem("IsOnTrack", 1, 1, false, "1=Car on track physics running with player in car", "") },
            { TelemetryVar.IsOnTrackCar, new VarItem("IsOnTrackCar", 1, 1, false, "1=Car on track physics running", "") },
            { TelemetryVar.IsReplayPlaying, new VarItem("IsReplayPlaying", 1, 1, false, "0=replay not playing  1=replay playing", "") },
            { TelemetryVar.Lap, new VarItem("Lap", 2, 1, false, "Laps started count", "") },
            { TelemetryVar.LapBestLap, new VarItem("LapBestLap", 2, 1, false, "Players best lap number", "") },
            { TelemetryVar.LapBestLapTime, new VarItem("LapBestLapTime", 4, 1, false, "Players best lap time", "s") },
            { TelemetryVar.LapBestNLapLap, new VarItem("LapBestNLapLap", 2, 1, false, "Player last lap in best N average lap time", "") },
            { TelemetryVar.LapBestNLapTime, new VarItem("LapBestNLapTime", 4, 1, false, "Player best N average lap time", "s") },
            { TelemetryVar.LapCompleted, new VarItem("LapCompleted", 2, 1, false, "Laps completed count", "") },
            { TelemetryVar.LapCurrentLapTime, new VarItem("LapCurrentLapTime", 4, 1, false, "Estimate of players current lap time as shown in F3 box", "s") },
            { TelemetryVar.LapDeltaToBestLap, new VarItem("LapDeltaToBestLap", 4, 1, false, "Delta time for best lap", "s") },
            { TelemetryVar.LapDeltaToBestLap_DD, new VarItem("LapDeltaToBestLap_DD", 4, 1, false, "Rate of change of delta time for best lap", "s/s") },
            { TelemetryVar.LapDeltaToBestLap_OK, new VarItem("LapDeltaToBestLap_OK", 1, 1, false, "Delta time for best lap is valid", "") },
            { TelemetryVar.LapDeltaToOptimalLap, new VarItem("LapDeltaToOptimalLap", 4, 1, false, "Delta time for optimal lap", "s") },
            { TelemetryVar.LapDeltaToOptimalLap_DD, new VarItem("LapDeltaToOptimalLap_DD", 4, 1, false, "Rate of change of delta time for optimal lap", "s/s") },
            { TelemetryVar.LapDeltaToOptimalLap_OK, new VarItem("LapDeltaToOptimalLap_OK", 1, 1, false, "Delta time for optimal lap is valid", "") },
            { TelemetryVar.LapDeltaToSessionBestLap, new VarItem("LapDeltaToSessionBestLap", 4, 1, false, "Delta time for session best lap", "s") },
            { TelemetryVar.LapDeltaToSessionBestLap_DD, new VarItem("LapDeltaToSessionBestLap_DD", 4, 1, false, "Rate of change of delta time for session best lap", "s/s") },
            { TelemetryVar.LapDeltaToSessionBestLap_OK, new VarItem("LapDeltaToSessionBestLap_OK", 1, 1, false, "Delta time for session best lap is valid", "") },
            { TelemetryVar.LapDeltaToSessionLastlLap, new VarItem("LapDeltaToSessionLastlLap", 4, 1, false, "Delta time for session last lap", "s") },
            { TelemetryVar.LapDeltaToSessionLastlLap_DD, new VarItem("LapDeltaToSessionLastlLap_DD", 4, 1, false, "Rate of change of delta time for session last lap", "s/s") },
            { TelemetryVar.LapDeltaToSessionLastlLap_OK, new VarItem("LapDeltaToSessionLastlLap_OK", 1, 1, false, "Delta time for session last lap is valid", "") },
            { TelemetryVar.LapDeltaToSessionOptimalLap, new VarItem("LapDeltaToSessionOptimalLap", 4, 1, false, "Delta time for session optimal lap", "s") },
            { TelemetryVar.LapDeltaToSessionOptimalLap_DD, new VarItem("LapDeltaToSessionOptimalLap_DD", 4, 1, false, "Rate of change of delta time for session optimal lap", "s/s") },
            { TelemetryVar.LapDeltaToSessionOptimalLap_OK, new VarItem("LapDeltaToSessionOptimalLap_OK", 1, 1, false, "Delta time for session optimal lap is valid", "") },
            { TelemetryVar.LapDist, new VarItem("LapDist", 4, 1, false, "Meters traveled from S/F this lap", "m") },
            { TelemetryVar.LapDistPct, new VarItem("LapDistPct", 4, 1, false, "Percentage distance around lap", "%") },
            { TelemetryVar.LapLasNLapSeq, new VarItem("LapLasNLapSeq", 2, 1, false, "Player num consecutive clean laps completed for N average", "") },
            { TelemetryVar.LapLastLapTime, new VarItem("LapLastLapTime", 4, 1, false, "Players last lap time", "s") },
            { TelemetryVar.LapLastNLapTime, new VarItem("LapLastNLapTime", 4, 1, false, "Player last N average lap time", "s") },
            { TelemetryVar.Lat, new VarItem("Lat", 5, 1, false, "Latitude in decimal degrees", "deg") },
            { TelemetryVar.LatAccel, new VarItem("LatAccel", 4, 1, false, "Lateral acceleration (including gravity)", "m/s^2") },
            { TelemetryVar.LatAccel_ST, new VarItem("LatAccel_ST", 4, 6, true, "Lateral acceleration (including gravity) at 360 Hz", "m/s^2") },
            { TelemetryVar.LeftTireSetsAvailable, new VarItem("LeftTireSetsAvailable", 2, 1, false, "How many left tire sets are remaining  255 is unlimited", "") },
            { TelemetryVar.LeftTireSetsUsed, new VarItem("LeftTireSetsUsed", 2, 1, false, "How many left tire sets used so far", "") },
            { TelemetryVar.LFbrakeLinePress, new VarItem("LFbrakeLinePress", 4, 1, false, "LF brake line pressure", "bar") },
            { TelemetryVar.LFcoldPressure, new VarItem("LFcoldPressure", 4, 1, false, "LF tire cold pressure  as set in the garage", "kPa") },
            { TelemetryVar.LFodometer, new VarItem("LFodometer", 4, 1, false, "LF distance tire traveled since being placed on car", "m") },
            { TelemetryVar.LFpressure, new VarItem("LFpressure", 4, 1, false, "LF tire pressure", "kPa") },
            { TelemetryVar.LFrideHeight, new VarItem("LFrideHeight", 4, 1, false, "LF ride height", "m") },
            { TelemetryVar.LFshockDefl, new VarItem("LFshockDefl", 4, 1, false, "LF shock deflection", "m") },
            { TelemetryVar.LFshockDefl_ST, new VarItem("LFshockDefl_ST", 4, 6, true, "LF shock deflection at 360 Hz", "m") },
            { TelemetryVar.LFshockVel, new VarItem("LFshockVel", 4, 1, false, "LF shock velocity", "m/s") },
            { TelemetryVar.LFshockVel_ST, new VarItem("LFshockVel_ST", 4, 6, true, "LF shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.LFSHshockDefl, new VarItem("LFSHshockDefl", 4, 1, false, "LFSH shock deflection", "m") },
            { TelemetryVar.LFSHshockDefl_ST, new VarItem("LFSHshockDefl_ST", 4, 6, true, "LFSH shock deflection at 360 Hz", "m") },
            { TelemetryVar.LFSHshockVel, new VarItem("LFSHshockVel", 4, 1, false, "LFSH shock velocity", "m/s") },
            { TelemetryVar.LFSHshockVel_ST, new VarItem("LFSHshockVel_ST", 4, 6, true, "LFSH shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.LFspeed, new VarItem("LFspeed", 4, 1, false, "LF wheel speed", "m/s") },
            { TelemetryVar.LFtempCL, new VarItem("LFtempCL", 4, 1, false, "LF tire left carcass temperature", "C") },
            { TelemetryVar.LFtempCM, new VarItem("LFtempCM", 4, 1, false, "LF tire middle carcass temperature", "C") },
            { TelemetryVar.LFtempCR, new VarItem("LFtempCR", 4, 1, false, "LF tire right carcass temperature", "C") },
            { TelemetryVar.LFtempL, new VarItem("LFtempL", 4, 1, false, "LF tire left surface temperature", "C") },
            { TelemetryVar.LFtempM, new VarItem("LFtempM", 4, 1, false, "LF tire middle surface temperature", "C") },
            { TelemetryVar.LFtempR, new VarItem("LFtempR", 4, 1, false, "LF tire right surface temperature", "C") },
            { TelemetryVar.LFTiresAvailable, new VarItem("LFTiresAvailable", 2, 1, false, "How many left front tires are remaining  255 is unlimited", "") },
            { TelemetryVar.LFTiresUsed, new VarItem("LFTiresUsed", 2, 1, false, "How many left front tires used so far", "") },
            { TelemetryVar.LFwearL, new VarItem("LFwearL", 4, 1, false, "LF tire left percent tread remaining", "%") },
            { TelemetryVar.LFwearM, new VarItem("LFwearM", 4, 1, false, "LF tire middle percent tread remaining", "%") },
            { TelemetryVar.LFwearR, new VarItem("LFwearR", 4, 1, false, "LF tire right percent tread remaining", "%") },
            { TelemetryVar.LoadNumTextures, new VarItem("LoadNumTextures", 1, 1, false, "True if the car_num texture will be loaded", "") },
            { TelemetryVar.Lon, new VarItem("Lon", 5, 1, false, "Longitude in decimal degrees", "deg") },
            { TelemetryVar.LongAccel, new VarItem("LongAccel", 4, 1, false, "Longitudinal acceleration (including gravity)", "m/s^2") },
            { TelemetryVar.LongAccel_ST, new VarItem("LongAccel_ST", 4, 6, true, "Longitudinal acceleration (including gravity) at 360 Hz", "m/s^2") },
            { TelemetryVar.LR2shockDefl, new VarItem("LR2shockDefl", 4, 1, false, "LR2 shock deflection", "m") },
            { TelemetryVar.LR2shockDefl_ST, new VarItem("LR2shockDefl_ST", 4, 6, true, "LR2 shock deflection at 360 Hz", "m") },
            { TelemetryVar.LR2shockVel, new VarItem("LR2shockVel", 4, 1, false, "LR2 shock velocity", "m/s") },
            { TelemetryVar.LR2shockVel_ST, new VarItem("LR2shockVel_ST", 4, 6, true, "LR2 shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.LRbrakeLinePress, new VarItem("LRbrakeLinePress", 4, 1, false, "LR brake line pressure", "bar") },
            { TelemetryVar.LRcoldPressure, new VarItem("LRcoldPressure", 4, 1, false, "LR tire cold pressure  as set in the garage", "kPa") },
            { TelemetryVar.LRodometer, new VarItem("LRodometer", 4, 1, false, "LR distance tire traveled since being placed on car", "m") },
            { TelemetryVar.LRpressure, new VarItem("LRpressure", 4, 1, false, "LR tire pressure", "kPa") },
            { TelemetryVar.LRrideHeight, new VarItem("LRrideHeight", 4, 1, false, "LR ride height", "m") },
            { TelemetryVar.LRshockDefl, new VarItem("LRshockDefl", 4, 1, false, "LR shock deflection", "m") },
            { TelemetryVar.LRshockDefl_ST, new VarItem("LRshockDefl_ST", 4, 6, true, "LR shock deflection at 360 Hz", "m") },
            { TelemetryVar.LRshockVel, new VarItem("LRshockVel", 4, 1, false, "LR shock velocity", "m/s") },
            { TelemetryVar.LRshockVel_ST, new VarItem("LRshockVel_ST", 4, 6, true, "LR shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.LRspeed, new VarItem("LRspeed", 4, 1, false, "LR wheel speed", "m/s") },
            { TelemetryVar.LRtempCL, new VarItem("LRtempCL", 4, 1, false, "LR tire left carcass temperature", "C") },
            { TelemetryVar.LRtempCM, new VarItem("LRtempCM", 4, 1, false, "LR tire middle carcass temperature", "C") },
            { TelemetryVar.LRtempCR, new VarItem("LRtempCR", 4, 1, false, "LR tire right carcass temperature", "C") },
            { TelemetryVar.LRtempL, new VarItem("LRtempL", 4, 1, false, "LR tire left surface temperature", "C") },
            { TelemetryVar.LRtempM, new VarItem("LRtempM", 4, 1, false, "LR tire middle surface temperature", "C") },
            { TelemetryVar.LRtempR, new VarItem("LRtempR", 4, 1, false, "LR tire right surface temperature", "C") },
            { TelemetryVar.LRTiresAvailable, new VarItem("LRTiresAvailable", 2, 1, false, "How many left rear tires are remaining  255 is unlimited", "") },
            { TelemetryVar.LRTiresUsed, new VarItem("LRTiresUsed", 2, 1, false, "How many left rear tires used so far", "") },
            { TelemetryVar.LRwearL, new VarItem("LRwearL", 4, 1, false, "LR tire left percent tread remaining", "%") },
            { TelemetryVar.LRwearM, new VarItem("LRwearM", 4, 1, false, "LR tire middle percent tread remaining", "%") },
            { TelemetryVar.LRwearR, new VarItem("LRwearR", 4, 1, false, "LR tire right percent tread remaining", "%") },
            { TelemetryVar.ManifoldPress, new VarItem("ManifoldPress", 4, 1, false, "Engine manifold pressure", "bar") },
            { TelemetryVar.ManualBoost, new VarItem("ManualBoost", 1, 1, false, "Hybrid manual boost state", "") },
            { TelemetryVar.ManualNoBoost, new VarItem("ManualNoBoost", 1, 1, false, "Hybrid manual no boost state", "") },
            { TelemetryVar.MemPageFaultSec, new VarItem("MemPageFaultSec", 4, 1, false, "Memory page faults per second", "") },
            { TelemetryVar.MemSoftPageFaultSec, new VarItem("MemSoftPageFaultSec", 4, 1, false, "Memory soft page faults per second", "") },
            { TelemetryVar.OilLevel, new VarItem("OilLevel", 4, 1, false, "Engine oil level", "l") },
            { TelemetryVar.OilPress, new VarItem("OilPress", 4, 1, false, "Engine oil pressure", "bar") },
            { TelemetryVar.OilTemp, new VarItem("OilTemp", 4, 1, false, "Engine oil temperature", "C") },
            { TelemetryVar.OkToReloadTextures, new VarItem("OkToReloadTextures", 1, 1, false, "True if it is ok to reload car textures at this time", "") },
            { TelemetryVar.OnPitRoad, new VarItem("OnPitRoad", 1, 1, false, "Is the player car on pit road between the cones", "") },
            { TelemetryVar.P2P_Count, new VarItem("P2P_Count", 2, 1, false, "Push2Pass count of usage (or remaining in Race) on your car", "") },
            { TelemetryVar.P2P_Status, new VarItem("P2P_Status", 1, 1, false, "Push2Pass active or not on your car", "") },
            { TelemetryVar.PaceMode, new VarItem("PaceMode", 2, 1, false, "Are we pacing or not", "PaceMode") },
            { TelemetryVar.Pitch, new VarItem("Pitch", 4, 1, false, "Pitch orientation", "rad") },
            { TelemetryVar.PitchRate, new VarItem("PitchRate", 4, 1, false, "Pitch rate", "rad/s") },
            { TelemetryVar.PitchRate_ST, new VarItem("PitchRate_ST", 4, 6, true, "Pitch rate at 360 Hz", "rad/s") },
            { TelemetryVar.PitOptRepairLeft, new VarItem("PitOptRepairLeft", 4, 1, false, "Time left for optional repairs if repairs are active", "s") },
            { TelemetryVar.PitRepairLeft, new VarItem("PitRepairLeft", 4, 1, false, "Time left for mandatory pit repairs if repairs are active", "s") },
            { TelemetryVar.PitsOpen, new VarItem("PitsOpen", 1, 1, false, "True if pit stop is allowed for the current player", "") },
            { TelemetryVar.PitstopActive, new VarItem("PitstopActive", 1, 1, false, "Is the player getting pit stop service", "") },
            { TelemetryVar.PitSvFlags, new VarItem("PitSvFlags", 3, 1, false, "Bitfield of pit service checkboxes", "PitSvFlags") },
            { TelemetryVar.PitSvFuel, new VarItem("PitSvFuel", 4, 1, false, "Pit service fuel add amount", "l or kWh") },
            { TelemetryVar.PitSvLFP, new VarItem("PitSvLFP", 4, 1, false, "Pit service left front tire pressure", "kPa") },
            { TelemetryVar.PitSvLRP, new VarItem("PitSvLRP", 4, 1, false, "Pit service left rear tire pressure", "kPa") },
            { TelemetryVar.PitSvRFP, new VarItem("PitSvRFP", 4, 1, false, "Pit service right front tire pressure", "kPa") },
            { TelemetryVar.PitSvRRP, new VarItem("PitSvRRP", 4, 1, false, "Pit service right rear tire pressure", "kPa") },
            { TelemetryVar.PitSvTireCompound, new VarItem("PitSvTireCompound", 2, 1, false, "Pit service pending tire compound", "") },
            { TelemetryVar.PlayerCarClass, new VarItem("PlayerCarClass", 2, 1, false, "Player car class id", "") },
            { TelemetryVar.PlayerCarClassPosition, new VarItem("PlayerCarClassPosition", 2, 1, false, "Players class position in race", "") },
            { TelemetryVar.PlayerCarDriverIncidentCount, new VarItem("PlayerCarDriverIncidentCount", 2, 1, false, "Teams current drivers incident count for this session", "") },
            { TelemetryVar.PlayerCarDryTireSetLimit, new VarItem("PlayerCarDryTireSetLimit", 2, 1, false, "Players dry tire set limit", "") },
            { TelemetryVar.PlayerCarIdx, new VarItem("PlayerCarIdx", 2, 1, false, "Players carIdx", "") },
            { TelemetryVar.PlayerCarInPitStall, new VarItem("PlayerCarInPitStall", 1, 1, false, "Players car is properly in their pitstall", "") },
            { TelemetryVar.PlayerCarMyIncidentCount, new VarItem("PlayerCarMyIncidentCount", 2, 1, false, "Players own incident count for this session", "") },
            { TelemetryVar.PlayerCarPitSvStatus, new VarItem("PlayerCarPitSvStatus", 2, 1, false, "Players car pit service status bits", "PitServiceStatus") },
            { TelemetryVar.PlayerCarPosition, new VarItem("PlayerCarPosition", 2, 1, false, "Players position in race", "") },
            { TelemetryVar.PlayerCarPowerAdjust, new VarItem("PlayerCarPowerAdjust", 4, 1, false, "Players power adjust", "%") },
            { TelemetryVar.PlayerCarSLBlinkRPM, new VarItem("PlayerCarSLBlinkRPM", 4, 1, false, "Shift light blink rpm", "revs/min") },
            { TelemetryVar.PlayerCarSLFirstRPM, new VarItem("PlayerCarSLFirstRPM", 4, 1, false, "Shift light first light rpm", "revs/min") },
            { TelemetryVar.PlayerCarSLLastRPM, new VarItem("PlayerCarSLLastRPM", 4, 1, false, "Shift light last light rpm", "revs/min") },
            { TelemetryVar.PlayerCarSLShiftRPM, new VarItem("PlayerCarSLShiftRPM", 4, 1, false, "Shift light shift rpm", "revs/min") },
            { TelemetryVar.PlayerCarTeamIncidentCount, new VarItem("PlayerCarTeamIncidentCount", 2, 1, false, "Players team incident count for this session", "") },
            { TelemetryVar.PlayerCarTowTime, new VarItem("PlayerCarTowTime", 4, 1, false, "Players car is being towed if time is greater than zero", "s") },
            { TelemetryVar.PlayerCarWeightPenalty, new VarItem("PlayerCarWeightPenalty", 4, 1, false, "Players weight penalty", "kg") },
            { TelemetryVar.PlayerFastRepairsUsed, new VarItem("PlayerFastRepairsUsed", 2, 1, false, "Players car number of fast repairs used", "") },
            { TelemetryVar.PlayerIncidents, new VarItem("PlayerIncidents", 2, 1, false, "Log incidents that the player received", "IncidentFlags") },
            { TelemetryVar.PlayerTireCompound, new VarItem("PlayerTireCompound", 2, 1, false, "Players car current tire compound", "") },
            { TelemetryVar.PlayerTrackSurface, new VarItem("PlayerTrackSurface", 2, 1, false, "Players car track surface type", "TrackLocation") },
            { TelemetryVar.PlayerTrackSurfaceMaterial, new VarItem("PlayerTrackSurfaceMaterial", 2, 1, false, "Players car track surface material type", "TrackSurface") },
            { TelemetryVar.Precipitation, new VarItem("Precipitation", 4, 1, false, "Precipitation at start/finish line", "%") },
            { TelemetryVar.PushToPass, new VarItem("PushToPass", 1, 1, false, "Push to pass button state", "") },
            { TelemetryVar.PushToTalk, new VarItem("PushToTalk", 1, 1, false, "Push to talk button state", "") },
            { TelemetryVar.RaceLaps, new VarItem("RaceLaps", 2, 1, false, "Laps completed in race", "") },
            { TelemetryVar.RadioTransmitCarIdx, new VarItem("RadioTransmitCarIdx", 2, 1, false, "The car index of the current person speaking on the radio", "") },
            { TelemetryVar.RadioTransmitFrequencyIdx, new VarItem("RadioTransmitFrequencyIdx", 2, 1, false, "The frequency index of the current person speaking on the radio", "") },
            { TelemetryVar.RadioTransmitRadioIdx, new VarItem("RadioTransmitRadioIdx", 2, 1, false, "The radio index of the current person speaking on the radio", "") },
            { TelemetryVar.RearTireSetsAvailable, new VarItem("RearTireSetsAvailable", 2, 1, false, "How many rear tire sets are remaining  255 is unlimited", "") },
            { TelemetryVar.RearTireSetsUsed, new VarItem("RearTireSetsUsed", 2, 1, false, "How many rear tire sets used so far", "") },
            { TelemetryVar.RelativeHumidity, new VarItem("RelativeHumidity", 4, 1, false, "Relative Humidity at start/finish line", "%") },
            { TelemetryVar.ReplayFrameNum, new VarItem("ReplayFrameNum", 2, 1, false, "Integer replay frame number (60 per second)", "") },
            { TelemetryVar.ReplayFrameNumEnd, new VarItem("ReplayFrameNumEnd", 2, 1, false, "Integer replay frame number from end of tape", "") },
            { TelemetryVar.ReplayPlaySlowMotion, new VarItem("ReplayPlaySlowMotion", 1, 1, false, "0=not slow motion  1=replay is in slow motion", "") },
            { TelemetryVar.ReplayPlaySpeed, new VarItem("ReplayPlaySpeed", 2, 1, false, "Replay playback speed", "") },
            { TelemetryVar.ReplaySessionNum, new VarItem("ReplaySessionNum", 2, 1, false, "Replay session number", "") },
            { TelemetryVar.ReplaySessionTime, new VarItem("ReplaySessionTime", 5, 1, false, "Seconds since replay session start", "s") },
            { TelemetryVar.RFbrakeLinePress, new VarItem("RFbrakeLinePress", 4, 1, false, "RF brake line pressure", "bar") },
            { TelemetryVar.RFcoldPressure, new VarItem("RFcoldPressure", 4, 1, false, "RF tire cold pressure  as set in the garage", "kPa") },
            { TelemetryVar.RFodometer, new VarItem("RFodometer", 4, 1, false, "RF distance tire traveled since being placed on car", "m") },
            { TelemetryVar.RFpressure, new VarItem("RFpressure", 4, 1, false, "RF tire pressure", "kPa") },
            { TelemetryVar.RFrideHeight, new VarItem("RFrideHeight", 4, 1, false, "RF ride height", "m") },
            { TelemetryVar.RFshockDefl, new VarItem("RFshockDefl", 4, 1, false, "RF shock deflection", "m") },
            { TelemetryVar.RFshockDefl_ST, new VarItem("RFshockDefl_ST", 4, 6, true, "RF shock deflection at 360 Hz", "m") },
            { TelemetryVar.RFshockVel, new VarItem("RFshockVel", 4, 1, false, "RF shock velocity", "m/s") },
            { TelemetryVar.RFshockVel_ST, new VarItem("RFshockVel_ST", 4, 6, true, "RF shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.RFSHshockDefl, new VarItem("RFSHshockDefl", 4, 1, false, "RFSH shock deflection", "m") },
            { TelemetryVar.RFSHshockDefl_ST, new VarItem("RFSHshockDefl_ST", 4, 6, true, "RFSH shock deflection at 360 Hz", "m") },
            { TelemetryVar.RFSHshockVel, new VarItem("RFSHshockVel", 4, 1, false, "RFSH shock velocity", "m/s") },
            { TelemetryVar.RFSHshockVel_ST, new VarItem("RFSHshockVel_ST", 4, 6, true, "RFSH shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.RFspeed, new VarItem("RFspeed", 4, 1, false, "RF wheel speed", "m/s") },
            { TelemetryVar.RFtempCL, new VarItem("RFtempCL", 4, 1, false, "RF tire left carcass temperature", "C") },
            { TelemetryVar.RFtempCM, new VarItem("RFtempCM", 4, 1, false, "RF tire middle carcass temperature", "C") },
            { TelemetryVar.RFtempCR, new VarItem("RFtempCR", 4, 1, false, "RF tire right carcass temperature", "C") },
            { TelemetryVar.RFtempL, new VarItem("RFtempL", 4, 1, false, "RF tire left surface temperature", "C") },
            { TelemetryVar.RFtempM, new VarItem("RFtempM", 4, 1, false, "RF tire middle surface temperature", "C") },
            { TelemetryVar.RFtempR, new VarItem("RFtempR", 4, 1, false, "RF tire right surface temperature", "C") },
            { TelemetryVar.RFTiresAvailable, new VarItem("RFTiresAvailable", 2, 1, false, "How many right front tires are remaining  255 is unlimited", "") },
            { TelemetryVar.RFTiresUsed, new VarItem("RFTiresUsed", 2, 1, false, "How many right front tires used so far", "") },
            { TelemetryVar.RFwearL, new VarItem("RFwearL", 4, 1, false, "RF tire left percent tread remaining", "%") },
            { TelemetryVar.RFwearM, new VarItem("RFwearM", 4, 1, false, "RF tire middle percent tread remaining", "%") },
            { TelemetryVar.RFwearR, new VarItem("RFwearR", 4, 1, false, "RF tire right percent tread remaining", "%") },
            { TelemetryVar.RightTireSetsAvailable, new VarItem("RightTireSetsAvailable", 2, 1, false, "How many right tire sets are remaining  255 is unlimited", "") },
            { TelemetryVar.RightTireSetsUsed, new VarItem("RightTireSetsUsed", 2, 1, false, "How many right tire sets used so far", "") },
            { TelemetryVar.Roll, new VarItem("Roll", 4, 1, false, "Roll orientation", "rad") },
            { TelemetryVar.RollRate, new VarItem("RollRate", 4, 1, false, "Roll rate", "rad/s") },
            { TelemetryVar.RollRate_ST, new VarItem("RollRate_ST", 4, 6, true, "Roll rate at 360 Hz", "rad/s") },
            { TelemetryVar.RPM, new VarItem("RPM", 4, 1, false, "Engine rpm", "revs/min") },
            { TelemetryVar.RRbrakeLinePress, new VarItem("RRbrakeLinePress", 4, 1, false, "RR brake line pressure", "bar") },
            { TelemetryVar.RRcoldPressure, new VarItem("RRcoldPressure", 4, 1, false, "RR tire cold pressure  as set in the garage", "kPa") },
            { TelemetryVar.RRodometer, new VarItem("RRodometer", 4, 1, false, "RR distance tire traveled since being placed on car", "m") },
            { TelemetryVar.RRpressure, new VarItem("RRpressure", 4, 1, false, "RR tire pressure", "kPa") },
            { TelemetryVar.RRrideHeight, new VarItem("RRrideHeight", 4, 1, false, "RR ride height", "m") },
            { TelemetryVar.RRshockDefl, new VarItem("RRshockDefl", 4, 1, false, "RR shock deflection", "m") },
            { TelemetryVar.RRshockDefl_ST, new VarItem("RRshockDefl_ST", 4, 6, true, "RR shock deflection at 360 Hz", "m") },
            { TelemetryVar.RRshockVel, new VarItem("RRshockVel", 4, 1, false, "RR shock velocity", "m/s") },
            { TelemetryVar.RRshockVel_ST, new VarItem("RRshockVel_ST", 4, 6, true, "RR shock velocity at 360 Hz", "m/s") },
            { TelemetryVar.RRspeed, new VarItem("RRspeed", 4, 1, false, "RR wheel speed", "m/s") },
            { TelemetryVar.RRtempCL, new VarItem("RRtempCL", 4, 1, false, "RR tire left carcass temperature", "C") },
            { TelemetryVar.RRtempCM, new VarItem("RRtempCM", 4, 1, false, "RR tire middle carcass temperature", "C") },
            { TelemetryVar.RRtempCR, new VarItem("RRtempCR", 4, 1, false, "RR tire right carcass temperature", "C") },
            { TelemetryVar.RRtempL, new VarItem("RRtempL", 4, 1, false, "RR tire left surface temperature", "C") },
            { TelemetryVar.RRtempM, new VarItem("RRtempM", 4, 1, false, "RR tire middle surface temperature", "C") },
            { TelemetryVar.RRtempR, new VarItem("RRtempR", 4, 1, false, "RR tire right surface temperature", "C") },
            { TelemetryVar.RRTiresAvailable, new VarItem("RRTiresAvailable", 2, 1, false, "How many right rear tires are remaining  255 is unlimited", "") },
            { TelemetryVar.RRTiresUsed, new VarItem("RRTiresUsed", 2, 1, false, "How many right rear tires used so far", "") },
            { TelemetryVar.RRwearL, new VarItem("RRwearL", 4, 1, false, "RR tire left percent tread remaining", "%") },
            { TelemetryVar.RRwearM, new VarItem("RRwearM", 4, 1, false, "RR tire middle percent tread remaining", "%") },
            { TelemetryVar.RRwearR, new VarItem("RRwearR", 4, 1, false, "RR tire right percent tread remaining", "%") },
            { TelemetryVar.SessionFlags, new VarItem("SessionFlags", 3, 1, false, "Session flags", "SessionFlags") },
            { TelemetryVar.SessionJokerLapsRemain, new VarItem("SessionJokerLapsRemain", 2, 1, false, "Joker laps remaining to be taken", "") },
            { TelemetryVar.SessionLapsRemain, new VarItem("SessionLapsRemain", 2, 1, false, "Old laps left till session ends use SessionLapsRemainEx", "") },
            { TelemetryVar.SessionLapsRemainEx, new VarItem("SessionLapsRemainEx", 2, 1, false, "New improved laps left till session ends", "") },
            { TelemetryVar.SessionLapsTotal, new VarItem("SessionLapsTotal", 2, 1, false, "Total number of laps in session", "") },
            { TelemetryVar.SessionNum, new VarItem("SessionNum", 2, 1, false, "Session number", "") },
            { TelemetryVar.SessionOnJokerLap, new VarItem("SessionOnJokerLap", 1, 1, false, "Player is currently completing a joker lap", "") },
            { TelemetryVar.SessionState, new VarItem("SessionState", 2, 1, false, "Session state", "SessionState") },
            { TelemetryVar.SessionTick, new VarItem("SessionTick", 2, 1, false, "Current update number", "") },
            { TelemetryVar.SessionTime, new VarItem("SessionTime", 5, 1, false, "Seconds since session start", "s") },
            { TelemetryVar.SessionTimeOfDay, new VarItem("SessionTimeOfDay", 4, 1, false, "Time of day in seconds", "s") },
            { TelemetryVar.SessionTimeRemain, new VarItem("SessionTimeRemain", 5, 1, false, "Seconds left till session ends", "s") },
            { TelemetryVar.SessionTimeTotal, new VarItem("SessionTimeTotal", 5, 1, false, "Total number of seconds in session", "s") },
            { TelemetryVar.SessionUniqueID, new VarItem("SessionUniqueID", 2, 1, false, "Session ID", "") },
            { TelemetryVar.Shifter, new VarItem("Shifter", 2, 1, false, "Log inputs from the players shifter control", "") },
            { TelemetryVar.ShiftGrindRPM, new VarItem("ShiftGrindRPM", 4, 1, false, "RPM of shifter grinding noise", "RPM") },
            { TelemetryVar.ShiftIndicatorPct, new VarItem("ShiftIndicatorPct", 4, 1, false, "DEPRECATED use DriverCarSLBlinkRPM instead", "%") },
            { TelemetryVar.ShiftPowerPct, new VarItem("ShiftPowerPct", 4, 1, false, "Friction torque applied to gears when shifting or grinding", "%") },
            { TelemetryVar.Skies, new VarItem("Skies", 2, 1, false, "Skies (0=clear/1=p cloudy/2=m cloudy/3=overcast)", "") },
            { TelemetryVar.SolarAltitude, new VarItem("SolarAltitude", 4, 1, false, "Sun angle above horizon in radians", "rad") },
            { TelemetryVar.SolarAzimuth, new VarItem("SolarAzimuth", 4, 1, false, "Sun angle clockwise from north in radians", "rad") },
            { TelemetryVar.Speed, new VarItem("Speed", 4, 1, false, "GPS vehicle speed", "m/s") },
            { TelemetryVar.SteeringFFBEnabled, new VarItem("SteeringFFBEnabled", 1, 1, false, "Force feedback is enabled", "") },
            { TelemetryVar.SteeringWheelAngle, new VarItem("SteeringWheelAngle", 4, 1, false, "Steering wheel angle", "rad") },
            { TelemetryVar.SteeringWheelAngleMax, new VarItem("SteeringWheelAngleMax", 4, 1, false, "Steering wheel max angle", "rad") },
            { TelemetryVar.SteeringWheelLimiter, new VarItem("SteeringWheelLimiter", 4, 1, false, "Force feedback limiter strength limits impacts and oscillation", "%") },
            { TelemetryVar.SteeringWheelMaxForceNm, new VarItem("SteeringWheelMaxForceNm", 4, 1, false, "Value of strength or max force slider in Nm for FFB", "N*m") },
            { TelemetryVar.SteeringWheelPctDamper, new VarItem("SteeringWheelPctDamper", 4, 1, false, "Force feedback % max damping", "%") },
            { TelemetryVar.SteeringWheelPctIntensity, new VarItem("SteeringWheelPctIntensity", 4, 1, false, "Force feedback % max intensity", "%") },
            { TelemetryVar.SteeringWheelPctSmoothing, new VarItem("SteeringWheelPctSmoothing", 4, 1, false, "Force feedback % max smoothing", "%") },
            { TelemetryVar.SteeringWheelPctTorque, new VarItem("SteeringWheelPctTorque", 4, 1, false, "Force feedback % max torque on steering shaft unsigned", "%") },
            { TelemetryVar.SteeringWheelPctTorqueSign, new VarItem("SteeringWheelPctTorqueSign", 4, 1, false, "Force feedback % max torque on steering shaft signed", "%") },
            { TelemetryVar.SteeringWheelPctTorqueSignStops, new VarItem("SteeringWheelPctTorqueSignStops", 4, 1, false, "Force feedback % max torque on steering shaft signed stops", "%") },
            { TelemetryVar.SteeringWheelPeakForceNm, new VarItem("SteeringWheelPeakForceNm", 4, 1, false, "Peak torque mapping to direct input units for FFB", "N*m") },
            { TelemetryVar.SteeringWheelTorque, new VarItem("SteeringWheelTorque", 4, 1, false, "Output torque on steering shaft", "N*m") },
            { TelemetryVar.SteeringWheelTorque_ST, new VarItem("SteeringWheelTorque_ST", 4, 6, true, "Output torque on steering shaft at 360 Hz", "N*m") },
            { TelemetryVar.SteeringWheelUseLinear, new VarItem("SteeringWheelUseLinear", 1, 1, false, "True if steering wheel force is using linear mode", "") },
            { TelemetryVar.Throttle, new VarItem("Throttle", 4, 1, false, "0=off throttle to 1=full throttle", "%") },
            { TelemetryVar.ThrottleRaw, new VarItem("ThrottleRaw", 4, 1, false, "Raw throttle input 0=off throttle to 1=full throttle", "%") },
            { TelemetryVar.TireLF_RumblePitch, new VarItem("TireLF_RumblePitch", 4, 1, false, "Players LF Tire Sound rumblestrip pitch", "Hz") },
            { TelemetryVar.TireLR_RumblePitch, new VarItem("TireLR_RumblePitch", 4, 1, false, "Players LR Tire Sound rumblestrip pitch", "Hz") },
            { TelemetryVar.TireRF_RumblePitch, new VarItem("TireRF_RumblePitch", 4, 1, false, "Players RF Tire Sound rumblestrip pitch", "Hz") },
            { TelemetryVar.TireRR_RumblePitch, new VarItem("TireRR_RumblePitch", 4, 1, false, "Players RR Tire Sound rumblestrip pitch", "Hz") },
            { TelemetryVar.TireSetsAvailable, new VarItem("TireSetsAvailable", 2, 1, false, "How many tire sets are remaining  255 is unlimited", "") },
            { TelemetryVar.TireSetsUsed, new VarItem("TireSetsUsed", 2, 1, false, "How many tire sets used so far", "") },
            { TelemetryVar.TrackTemp, new VarItem("TrackTemp", 4, 1, false, "Deprecated  set to TrackTempCrew", "C") },
            { TelemetryVar.TrackTempCrew, new VarItem("TrackTempCrew", 4, 1, false, "Temperature of track measured by crew around track", "C") },
            { TelemetryVar.TrackWetness, new VarItem("TrackWetness", 2, 1, false, "How wet is the average track surface", "TrackWetness") },
            { TelemetryVar.VelocityX, new VarItem("VelocityX", 4, 1, false, "X velocity", "m/s") },
            { TelemetryVar.VelocityX_ST, new VarItem("VelocityX_ST", 4, 6, true, "X velocity", "m/s at 360 Hz") },
            { TelemetryVar.VelocityY, new VarItem("VelocityY", 4, 1, false, "Y velocity", "m/s") },
            { TelemetryVar.VelocityY_ST, new VarItem("VelocityY_ST", 4, 6, true, "Y velocity", "m/s at 360 Hz") },
            { TelemetryVar.VelocityZ, new VarItem("VelocityZ", 4, 1, false, "Z velocity", "m/s") },
            { TelemetryVar.VelocityZ_ST, new VarItem("VelocityZ_ST", 4, 6, true, "Z velocity", "m/s at 360 Hz") },
            { TelemetryVar.VertAccel, new VarItem("VertAccel", 4, 1, false, "Vertical acceleration (including gravity)", "m/s^2") },
            { TelemetryVar.VertAccel_ST, new VarItem("VertAccel_ST", 4, 6, true, "Vertical acceleration (including gravity) at 360 Hz", "m/s^2") },
            { TelemetryVar.VidCapActive, new VarItem("VidCapActive", 1, 1, false, "True if video currently being captured", "") },
            { TelemetryVar.VidCapEnabled, new VarItem("VidCapEnabled", 1, 1, false, "True if video capture system is enabled", "") },
            { TelemetryVar.Voltage, new VarItem("Voltage", 4, 1, false, "Engine voltage", "V") },
            { TelemetryVar.WaterLevel, new VarItem("WaterLevel", 4, 1, false, "Engine coolant level", "l") },
            { TelemetryVar.WaterTemp, new VarItem("WaterTemp", 4, 1, false, "Engine coolant temp", "C") },
            { TelemetryVar.WeatherDeclaredWet, new VarItem("WeatherDeclaredWet", 1, 1, false, "The steward says rain tires can be used", "") },
            { TelemetryVar.WindDir, new VarItem("WindDir", 4, 1, false, "Wind direction at start/finish line", "rad") },
            { TelemetryVar.WindVel, new VarItem("WindVel", 4, 1, false, "Wind velocity at start/finish line", "m/s") },
            { TelemetryVar.Yaw, new VarItem("Yaw", 4, 1, false, "Yaw orientation", "rad") },
            { TelemetryVar.YawNorth, new VarItem("YawNorth", 4, 1, false, "Yaw orientation relative to north", "rad") },
            { TelemetryVar.YawRate, new VarItem("YawRate", 4, 1, false, "Yaw rate", "rad/s") },
            { TelemetryVar.YawRate_ST, new VarItem("YawRate_ST", 4, 6, true, "Yaw rate at 360 Hz", "rad/s") },
        };
    }
}



