/**
 * Copyright (C)2024 Scott Velez
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.using Microsoft.CodeAnalysis;
**/

/* 
 * This file is used by the code generation tooling to generate the TelemetryData structure with strongly typed properties.
 * It is NOT meant to be used directly.
 * 
**/

using System;
using System.Collections.Generic;

namespace SVappsLAB.iRacingTelemetrySDK
{
    public record struct VarItem(string Name, int Type, int Length, bool IsTimeValue, string Desc, string Units);
    public class iRacingVars
    {
        // a dictionary of all known variables from the iRacing SDK - both live sessions and offline ibt files
        // this data is used by the code generation to generate typed variables for your code.
        public Dictionary<string, VarItem> Vars = new(StringComparer.OrdinalIgnoreCase)
        {
            { "AirDensity", new VarItem("AirDensity", 4, 1, false, "Density of air at start/finish line", "kg/m^3") },
            { "AirPressure", new VarItem("AirPressure", 4, 1, false, "Pressure of air at start/finish line", "Pa") },
            { "AirTemp", new VarItem("AirTemp", 4, 1, false, "Temperature of air at start/finish line", "C") },
            { "Alt", new VarItem("Alt", 4, 1, false, "Altitude in meters", "m") },
            { "Brake", new VarItem("Brake", 4, 1, false, "0=brake released to 1=max pedal force", "%") },
            { "BrakeABSactive", new VarItem("BrakeABSactive", 1, 1, false, "true if abs is currently reducing brake force pressure", "") },
            { "BrakeABScutPct", new VarItem("BrakeABScutPct", 4, 1, false, "Percent of brake force reduction caused by ABS system", "%") },
            { "BrakeRaw", new VarItem("BrakeRaw", 4, 1, false, "Raw brake input 0=brake released to 1=max pedal force", "%") },
            { "CFshockDefl", new VarItem("CFshockDefl", 4, 1, false, "CF shock deflection", "m") },
            { "CFshockDefl_ST", new VarItem("CFshockDefl_ST", 4, 6, true, "CF shock deflection at 360 Hz", "m") },
            { "CFshockVel", new VarItem("CFshockVel", 4, 1, false, "CF shock velocity", "m/s") },
            { "CFshockVel_ST", new VarItem("CFshockVel_ST", 4, 6, true, "CF shock velocity at 360 Hz", "m/s") },
            { "CRshockDefl", new VarItem("CRshockDefl", 4, 1, false, "CR shock deflection", "m") },
            { "CRshockDefl_ST", new VarItem("CRshockDefl_ST", 4, 6, true, "CR shock deflection at 360 Hz", "m") },
            { "CRshockVel", new VarItem("CRshockVel", 4, 1, false, "CR shock velocity", "m/s") },
            { "CRshockVel_ST", new VarItem("CRshockVel_ST", 4, 6, true, "CR shock velocity at 360 Hz", "m/s") },
            { "CamCameraNumber", new VarItem("CamCameraNumber", 2, 1, false, "Active camera number", "") },
            { "CamCameraState", new VarItem("CamCameraState", 3, 1, false, "State of camera system", "irsdk_CameraState") },
            { "CamCarIdx", new VarItem("CamCarIdx", 2, 1, false, "Active camera's focus car index", "") },
            { "CamGroupNumber", new VarItem("CamGroupNumber", 2, 1, false, "Active camera group number", "") },
            { "CarDistAhead", new VarItem("CarDistAhead", 4, 1, false, "Distance to first car in front of player in meters", "m") },
            { "CarDistBehind", new VarItem("CarDistBehind", 4, 1, false, "Distance to first car behind player in meters", "m") },
            { "CarIdxBestLapNum", new VarItem("CarIdxBestLapNum", 2, 64, false, "Cars best lap number", "") },
            { "CarIdxBestLapTime", new VarItem("CarIdxBestLapTime", 4, 64, false, "Cars best lap time", "s") },
            { "CarIdxClass", new VarItem("CarIdxClass", 2, 64, false, "Cars class id by car index", "") },
            { "CarIdxClassPosition", new VarItem("CarIdxClassPosition", 2, 64, false, "Cars class position in race by car index", "") },
            { "CarIdxEstTime", new VarItem("CarIdxEstTime", 4, 64, false, "Estimated time to reach current location on track", "s") },
            { "CarIdxF2Time", new VarItem("CarIdxF2Time", 4, 64, false, "Race time behind leader or fastest lap time otherwise", "s") },
            { "CarIdxFastRepairsUsed", new VarItem("CarIdxFastRepairsUsed", 2, 64, false, "How many fast repairs each car has used", "") },
            { "CarIdxGear", new VarItem("CarIdxGear", 2, 64, false, "-1=reverse  0=neutral  1..n=current gear by car index", "") },
            { "CarIdxLap", new VarItem("CarIdxLap", 2, 64, false, "Laps started by car index", "") },
            { "CarIdxLapCompleted", new VarItem("CarIdxLapCompleted", 2, 64, false, "Laps completed by car index", "") },
            { "CarIdxLapDistPct", new VarItem("CarIdxLapDistPct", 4, 64, false, "Percentage distance around lap by car index", "%") },
            { "CarIdxLastLapTime", new VarItem("CarIdxLastLapTime", 4, 64, false, "Cars last lap time", "s") },
            { "CarIdxOnPitRoad", new VarItem("CarIdxOnPitRoad", 1, 64, false, "On pit road between the cones by car index", "") },
            { "CarIdxP2P_Count", new VarItem("CarIdxP2P_Count", 2, 64, false, "Push2Pass count of usage (or remaining in Race)", "") },
            { "CarIdxP2P_Status", new VarItem("CarIdxP2P_Status", 1, 64, false, "Push2Pass active or not", "") },
            { "CarIdxPaceFlags", new VarItem("CarIdxPaceFlags", 3, 64, false, "Pacing status flags for each car", "irsdk_PaceFlags") },
            { "CarIdxPaceLine", new VarItem("CarIdxPaceLine", 2, 64, false, "What line cars are pacing in  or -1 if not pacing", "") },
            { "CarIdxPaceRow", new VarItem("CarIdxPaceRow", 2, 64, false, "What row cars are pacing in  or -1 if not pacing", "") },
            { "CarIdxPosition", new VarItem("CarIdxPosition", 2, 64, false, "Cars position in race by car index", "") },
            { "CarIdxQualTireCompound", new VarItem("CarIdxQualTireCompound", 2, 64, false, "Cars Qual tire compound", "") },
            { "CarIdxQualTireCompoundLocked", new VarItem("CarIdxQualTireCompoundLocked", 1, 64, false, "Cars Qual tire compound is locked-in", "") },
            { "CarIdxRPM", new VarItem("CarIdxRPM", 4, 64, false, "Engine rpm by car index", "revs/min") },
            { "CarIdxSessionFlags", new VarItem("CarIdxSessionFlags", 3, 64, false, "Session flags for each player", "irsdk_Flags") },
            { "CarIdxSteer", new VarItem("CarIdxSteer", 4, 64, false, "Steering wheel angle by car index", "rad") },
            { "CarIdxTireCompound", new VarItem("CarIdxTireCompound", 2, 64, false, "Cars current tire compound", "") },
            { "CarIdxTrackSurface", new VarItem("CarIdxTrackSurface", 2, 64, false, "Track surface type by car index", "irsdk_TrkLoc") },
            { "CarIdxTrackSurfaceMaterial", new VarItem("CarIdxTrackSurfaceMaterial", 2, 64, false, "Track surface material type by car index", "irsdk_TrkSurf") },
            { "CarLeftRight", new VarItem("CarLeftRight", 2, 1, false, "Notify if car is to the left or right of driver", "irsdk_CarLeftRight") },
            { "ChanAvgLatency", new VarItem("ChanAvgLatency", 4, 1, false, "Communications average latency", "s") },
            { "ChanClockSkew", new VarItem("ChanClockSkew", 4, 1, false, "Communications server clock skew", "s") },
            { "ChanLatency", new VarItem("ChanLatency", 4, 1, false, "Communications latency", "s") },
            { "ChanPartnerQuality", new VarItem("ChanPartnerQuality", 4, 1, false, "Partner communications quality", "%") },
            { "ChanQuality", new VarItem("ChanQuality", 4, 1, false, "Communications quality", "%") },
            { "Clutch", new VarItem("Clutch", 4, 1, false, "0=disengaged to 1=fully engaged", "%") },
            { "ClutchRaw", new VarItem("ClutchRaw", 4, 1, false, "Raw clutch input 0=disengaged to 1=fully engaged", "%") },
            { "CpuUsageBG", new VarItem("CpuUsageBG", 4, 1, false, "Percent of available tim bg thread took with a 1 sec avg", "%") },
            { "CpuUsageFG", new VarItem("CpuUsageFG", 4, 1, false, "Percent of available tim fg thread took with a 1 sec avg", "%") },
            { "DCDriversSoFar", new VarItem("DCDriversSoFar", 2, 1, false, "Number of team drivers who have run a stint", "") },
            { "DCLapStatus", new VarItem("DCLapStatus", 2, 1, false, "Status of driver change lap requirements", "") },
            { "DisplayUnits", new VarItem("DisplayUnits", 2, 1, false, "Default units for the user interface 0 = english 1 = metric", "") },
            { "DriverMarker", new VarItem("DriverMarker", 1, 1, false, "Driver activated flag", "") },
            { "Engine0_RPM", new VarItem("Engine0_RPM", 4, 1, false, "Engine0Engine rpm", "revs/min") },
            { "EngineWarnings", new VarItem("EngineWarnings", 3, 1, false, "Bitfield for warning lights", "irsdk_EngineWarnings") },
            { "EnterExitReset", new VarItem("EnterExitReset", 2, 1, false, "Indicate action the reset key will take 0 enter 1 exit 2 reset", "") },
            { "FastRepairAvailable", new VarItem("FastRepairAvailable", 2, 1, false, "How many fast repairs left  255 is unlimited", "") },
            { "FastRepairUsed", new VarItem("FastRepairUsed", 2, 1, false, "How many fast repairs used so far", "") },
            { "FogLevel", new VarItem("FogLevel", 4, 1, false, "Fog level at start/finish line", "%") },
            { "FrameRate", new VarItem("FrameRate", 4, 1, false, "Average frames per second", "fps") },
            { "FrontTireSetsAvailable", new VarItem("FrontTireSetsAvailable", 2, 1, false, "How many front tire sets are remaining  255 is unlimited", "") },
            { "FrontTireSetsUsed", new VarItem("FrontTireSetsUsed", 2, 1, false, "How many front tire sets used so far", "") },
            { "FuelLevel", new VarItem("FuelLevel", 4, 1, false, "Liters of fuel remaining", "l") },
            { "FuelLevelPct", new VarItem("FuelLevelPct", 4, 1, false, "Percent fuel remaining", "%") },
            { "FuelPress", new VarItem("FuelPress", 4, 1, false, "Engine fuel pressure", "bar") },
            { "FuelUsePerHour", new VarItem("FuelUsePerHour", 4, 1, false, "Engine fuel used instantaneous", "kg/h") },
            { "Gear", new VarItem("Gear", 2, 1, false, "-1=reverse  0=neutral  1..n=current gear", "") },
            { "GpuUsage", new VarItem("GpuUsage", 4, 1, false, "Percent of available tim gpu took with a 1 sec avg", "%") },
            { "HandbrakeRaw", new VarItem("HandbrakeRaw", 4, 1, false, "Raw handbrake input 0=handbrake released to 1=max force", "%") },
            { "IsDiskLoggingActive", new VarItem("IsDiskLoggingActive", 1, 1, false, "0=disk based telemetry file not being written  1=being written", "") },
            { "IsDiskLoggingEnabled", new VarItem("IsDiskLoggingEnabled", 1, 1, false, "0=disk based telemetry turned off  1=turned on", "") },
            { "IsGarageVisible", new VarItem("IsGarageVisible", 1, 1, false, "1=Garage screen is visible", "") },
            { "IsInGarage", new VarItem("IsInGarage", 1, 1, false, "1=Car in garage physics running", "") },
            { "IsOnTrack", new VarItem("IsOnTrack", 1, 1, false, "1=Car on track physics running with player in car", "") },
            { "IsOnTrackCar", new VarItem("IsOnTrackCar", 1, 1, false, "1=Car on track physics running", "") },
            { "IsReplayPlaying", new VarItem("IsReplayPlaying", 1, 1, false, "0=replay not playing  1=replay playing", "") },
            { "LFSHshockDefl", new VarItem("LFSHshockDefl", 4, 1, false, "LFSH shock deflection", "m") },
            { "LFSHshockDefl_ST", new VarItem("LFSHshockDefl_ST", 4, 6, true, "LFSH shock deflection at 360 Hz", "m") },
            { "LFSHshockVel", new VarItem("LFSHshockVel", 4, 1, false, "LFSH shock velocity", "m/s") },
            { "LFSHshockVel_ST", new VarItem("LFSHshockVel_ST", 4, 6, true, "LFSH shock velocity at 360 Hz", "m/s") },
            { "LFTiresAvailable", new VarItem("LFTiresAvailable", 2, 1, false, "How many left front tires are remaining  255 is unlimited", "") },
            { "LFTiresUsed", new VarItem("LFTiresUsed", 2, 1, false, "How many left front tires used so far", "") },
            { "LFbrakeLinePress", new VarItem("LFbrakeLinePress", 4, 1, false, "LF brake line pressure", "bar") },
            { "LFcoldPressure", new VarItem("LFcoldPressure", 4, 1, false, "LF tire cold pressure  as set in the garage", "kPa") },
            { "LFpressure", new VarItem("LFpressure", 4, 1, false, "LF tire pressure", "kPa") },
            { "LFrideHeight", new VarItem("LFrideHeight", 4, 1, false, "LF ride height", "m") },
            { "LFshockDefl", new VarItem("LFshockDefl", 4, 1, false, "LF shock deflection", "m") },
            { "LFshockDefl_ST", new VarItem("LFshockDefl_ST", 4, 6, true, "LF shock deflection at 360 Hz", "m") },
            { "LFshockVel", new VarItem("LFshockVel", 4, 1, false, "LF shock velocity", "m/s") },
            { "LFshockVel_ST", new VarItem("LFshockVel_ST", 4, 6, true, "LF shock velocity at 360 Hz", "m/s") },
            { "LFspeed", new VarItem("LFspeed", 4, 1, false, "LF wheel speed", "m/s") },
            { "LFtempCL", new VarItem("LFtempCL", 4, 1, false, "LF tire left carcass temperature", "C") },
            { "LFtempCM", new VarItem("LFtempCM", 4, 1, false, "LF tire middle carcass temperature", "C") },
            { "LFtempCR", new VarItem("LFtempCR", 4, 1, false, "LF tire right carcass temperature", "C") },
            { "LFtempL", new VarItem("LFtempL", 4, 1, false, "LF tire left surface temperature", "C") },
            { "LFtempM", new VarItem("LFtempM", 4, 1, false, "LF tire middle surface temperature", "C") },
            { "LFtempR", new VarItem("LFtempR", 4, 1, false, "LF tire right surface temperature", "C") },
            { "LFwearL", new VarItem("LFwearL", 4, 1, false, "LF tire left percent tread remaining", "%") },
            { "LFwearM", new VarItem("LFwearM", 4, 1, false, "LF tire middle percent tread remaining", "%") },
            { "LFwearR", new VarItem("LFwearR", 4, 1, false, "LF tire right percent tread remaining", "%") },
            { "LR2shockDefl", new VarItem("LR2shockDefl", 4, 1, false, "LR2 shock deflection", "m") },
            { "LR2shockDefl_ST", new VarItem("LR2shockDefl_ST", 4, 6, true, "LR2 shock deflection at 360 Hz", "m") },
            { "LR2shockVel", new VarItem("LR2shockVel", 4, 1, false, "LR2 shock velocity", "m/s") },
            { "LR2shockVel_ST", new VarItem("LR2shockVel_ST", 4, 6, true, "LR2 shock velocity at 360 Hz", "m/s") },
            { "LRTiresAvailable", new VarItem("LRTiresAvailable", 2, 1, false, "How many left rear tires are remaining  255 is unlimited", "") },
            { "LRTiresUsed", new VarItem("LRTiresUsed", 2, 1, false, "How many left rear tires used so far", "") },
            { "LRbrakeLinePress", new VarItem("LRbrakeLinePress", 4, 1, false, "LR brake line pressure", "bar") },
            { "LRcoldPressure", new VarItem("LRcoldPressure", 4, 1, false, "LR tire cold pressure  as set in the garage", "kPa") },
            { "LRpressure", new VarItem("LRpressure", 4, 1, false, "LR tire pressure", "kPa") },
            { "LRrideHeight", new VarItem("LRrideHeight", 4, 1, false, "LR ride height", "m") },
            { "LRshockDefl", new VarItem("LRshockDefl", 4, 1, false, "LR shock deflection", "m") },
            { "LRshockDefl_ST", new VarItem("LRshockDefl_ST", 4, 6, true, "LR shock deflection at 360 Hz", "m") },
            { "LRshockVel", new VarItem("LRshockVel", 4, 1, false, "LR shock velocity", "m/s") },
            { "LRshockVel_ST", new VarItem("LRshockVel_ST", 4, 6, true, "LR shock velocity at 360 Hz", "m/s") },
            { "LRspeed", new VarItem("LRspeed", 4, 1, false, "LR wheel speed", "m/s") },
            { "LRtempCL", new VarItem("LRtempCL", 4, 1, false, "LR tire left carcass temperature", "C") },
            { "LRtempCM", new VarItem("LRtempCM", 4, 1, false, "LR tire middle carcass temperature", "C") },
            { "LRtempCR", new VarItem("LRtempCR", 4, 1, false, "LR tire right carcass temperature", "C") },
            { "LRtempL", new VarItem("LRtempL", 4, 1, false, "LR tire left surface temperature", "C") },
            { "LRtempM", new VarItem("LRtempM", 4, 1, false, "LR tire middle surface temperature", "C") },
            { "LRtempR", new VarItem("LRtempR", 4, 1, false, "LR tire right surface temperature", "C") },
            { "LRwearL", new VarItem("LRwearL", 4, 1, false, "LR tire left percent tread remaining", "%") },
            { "LRwearM", new VarItem("LRwearM", 4, 1, false, "LR tire middle percent tread remaining", "%") },
            { "LRwearR", new VarItem("LRwearR", 4, 1, false, "LR tire right percent tread remaining", "%") },
            { "Lap", new VarItem("Lap", 2, 1, false, "Laps started count", "") },
            { "LapBestLap", new VarItem("LapBestLap", 2, 1, false, "Players best lap number", "") },
            { "LapBestLapTime", new VarItem("LapBestLapTime", 4, 1, false, "Players best lap time", "s") },
            { "LapBestNLapLap", new VarItem("LapBestNLapLap", 2, 1, false, "Player last lap in best N average lap time", "") },
            { "LapBestNLapTime", new VarItem("LapBestNLapTime", 4, 1, false, "Player best N average lap time", "s") },
            { "LapCompleted", new VarItem("LapCompleted", 2, 1, false, "Laps completed count", "") },
            { "LapCurrentLapTime", new VarItem("LapCurrentLapTime", 4, 1, false, "Estimate of players current lap time as shown in F3 box", "s") },
            { "LapDeltaToBestLap", new VarItem("LapDeltaToBestLap", 4, 1, false, "Delta time for best lap", "s") },
            { "LapDeltaToBestLap_DD", new VarItem("LapDeltaToBestLap_DD", 4, 1, false, "Rate of change of delta time for best lap", "s/s") },
            { "LapDeltaToBestLap_OK", new VarItem("LapDeltaToBestLap_OK", 1, 1, false, "Delta time for best lap is valid", "") },
            { "LapDeltaToOptimalLap", new VarItem("LapDeltaToOptimalLap", 4, 1, false, "Delta time for optimal lap", "s") },
            { "LapDeltaToOptimalLap_DD", new VarItem("LapDeltaToOptimalLap_DD", 4, 1, false, "Rate of change of delta time for optimal lap", "s/s") },
            { "LapDeltaToOptimalLap_OK", new VarItem("LapDeltaToOptimalLap_OK", 1, 1, false, "Delta time for optimal lap is valid", "") },
            { "LapDeltaToSessionBestLap", new VarItem("LapDeltaToSessionBestLap", 4, 1, false, "Delta time for session best lap", "s") },
            { "LapDeltaToSessionBestLap_DD", new VarItem("LapDeltaToSessionBestLap_DD", 4, 1, false, "Rate of change of delta time for session best lap", "s/s") },
            { "LapDeltaToSessionBestLap_OK", new VarItem("LapDeltaToSessionBestLap_OK", 1, 1, false, "Delta time for session best lap is valid", "") },
            { "LapDeltaToSessionLastlLap", new VarItem("LapDeltaToSessionLastlLap", 4, 1, false, "Delta time for session last lap", "s") },
            { "LapDeltaToSessionLastlLap_DD", new VarItem("LapDeltaToSessionLastlLap_DD", 4, 1, false, "Rate of change of delta time for session last lap", "s/s") },
            { "LapDeltaToSessionLastlLap_OK", new VarItem("LapDeltaToSessionLastlLap_OK", 1, 1, false, "Delta time for session last lap is valid", "") },
            { "LapDeltaToSessionOptimalLap", new VarItem("LapDeltaToSessionOptimalLap", 4, 1, false, "Delta time for session optimal lap", "s") },
            { "LapDeltaToSessionOptimalLap_DD", new VarItem("LapDeltaToSessionOptimalLap_DD", 4, 1, false, "Rate of change of delta time for session optimal lap", "s/s") },
            { "LapDeltaToSessionOptimalLap_OK", new VarItem("LapDeltaToSessionOptimalLap_OK", 1, 1, false, "Delta time for session optimal lap is valid", "") },
            { "LapDist", new VarItem("LapDist", 4, 1, false, "Meters traveled from S/F this lap", "m") },
            { "LapDistPct", new VarItem("LapDistPct", 4, 1, false, "Percentage distance around lap", "%") },
            { "LapLasNLapSeq", new VarItem("LapLasNLapSeq", 2, 1, false, "Player num consecutive clean laps completed for N average", "") },
            { "LapLastLapTime", new VarItem("LapLastLapTime", 4, 1, false, "Players last lap time", "s") },
            { "LapLastNLapTime", new VarItem("LapLastNLapTime", 4, 1, false, "Player last N average lap time", "s") },
            { "Lat", new VarItem("Lat", 5, 1, false, "Latitude in decimal degrees", "deg") },
            { "LatAccel", new VarItem("LatAccel", 4, 1, false, "Lateral acceleration (including gravity)", "m/s^2") },
            { "LatAccel_ST", new VarItem("LatAccel_ST", 4, 6, true, "Lateral acceleration (including gravity) at 360 Hz", "m/s^2") },
            { "LeftTireSetsAvailable", new VarItem("LeftTireSetsAvailable", 2, 1, false, "How many left tire sets are remaining  255 is unlimited", "") },
            { "LeftTireSetsUsed", new VarItem("LeftTireSetsUsed", 2, 1, false, "How many left tire sets used so far", "") },
            { "LoadNumTextures", new VarItem("LoadNumTextures", 1, 1, false, "True if the car_num texture will be loaded", "") },
            { "Lon", new VarItem("Lon", 5, 1, false, "Longitude in decimal degrees", "deg") },
            { "LongAccel", new VarItem("LongAccel", 4, 1, false, "Longitudinal acceleration (including gravity)", "m/s^2") },
            { "LongAccel_ST", new VarItem("LongAccel_ST", 4, 6, true, "Longitudinal acceleration (including gravity) at 360 Hz", "m/s^2") },
            { "ManifoldPress", new VarItem("ManifoldPress", 4, 1, false, "Engine manifold pressure", "bar") },
            { "ManualBoost", new VarItem("ManualBoost", 1, 1, false, "Hybrid manual boost state", "") },
            { "ManualNoBoost", new VarItem("ManualNoBoost", 1, 1, false, "Hybrid manual no boost state", "") },
            { "MemPageFaultSec", new VarItem("MemPageFaultSec", 4, 1, false, "Memory page faults per second", "") },
            { "MemSoftPageFaultSec", new VarItem("MemSoftPageFaultSec", 4, 1, false, "Memory soft page faults per second", "") },
            { "OilLevel", new VarItem("OilLevel", 4, 1, false, "Engine oil level", "l") },
            { "OilPress", new VarItem("OilPress", 4, 1, false, "Engine oil pressure", "bar") },
            { "OilTemp", new VarItem("OilTemp", 4, 1, false, "Engine oil temperature", "C") },
            { "OkToReloadTextures", new VarItem("OkToReloadTextures", 1, 1, false, "True if it is ok to reload car textures at this time", "") },
            { "OnPitRoad", new VarItem("OnPitRoad", 1, 1, false, "Is the player car on pit road between the cones", "") },
            { "P2P_Count", new VarItem("P2P_Count", 2, 1, false, "Push2Pass count of usage (or remaining in Race) on your car", "") },
            { "P2P_Status", new VarItem("P2P_Status", 1, 1, false, "Push2Pass active or not on your car", "") },
            { "PaceMode", new VarItem("PaceMode", 2, 1, false, "Are we pacing or not", "irsdk_PaceMode") },
            { "PitOptRepairLeft", new VarItem("PitOptRepairLeft", 4, 1, false, "Time left for optional repairs if repairs are active", "s") },
            { "PitRepairLeft", new VarItem("PitRepairLeft", 4, 1, false, "Time left for mandatory pit repairs if repairs are active", "s") },
            { "PitSvFlags", new VarItem("PitSvFlags", 3, 1, false, "Bitfield of pit service checkboxes", "irsdk_PitSvFlags") },
            { "PitSvFuel", new VarItem("PitSvFuel", 4, 1, false, "Pit service fuel add amount", "l or kWh") },
            { "PitSvLFP", new VarItem("PitSvLFP", 4, 1, false, "Pit service left front tire pressure", "kPa") },
            { "PitSvLRP", new VarItem("PitSvLRP", 4, 1, false, "Pit service left rear tire pressure", "kPa") },
            { "PitSvRFP", new VarItem("PitSvRFP", 4, 1, false, "Pit service right front tire pressure", "kPa") },
            { "PitSvRRP", new VarItem("PitSvRRP", 4, 1, false, "Pit service right rear tire pressure", "kPa") },
            { "PitSvTireCompound", new VarItem("PitSvTireCompound", 2, 1, false, "Pit service pending tire compound", "") },
            { "Pitch", new VarItem("Pitch", 4, 1, false, "Pitch orientation", "rad") },
            { "PitchRate", new VarItem("PitchRate", 4, 1, false, "Pitch rate", "rad/s") },
            { "PitchRate_ST", new VarItem("PitchRate_ST", 4, 6, true, "Pitch rate at 360 Hz", "rad/s") },
            { "PitsOpen", new VarItem("PitsOpen", 1, 1, false, "True if pit stop is allowed for the current player", "") },
            { "PitstopActive", new VarItem("PitstopActive", 1, 1, false, "Is the player getting pit stop service", "") },
            { "PlayerCarClass", new VarItem("PlayerCarClass", 2, 1, false, "Player car class id", "") },
            { "PlayerCarClassPosition", new VarItem("PlayerCarClassPosition", 2, 1, false, "Players class position in race", "") },
            { "PlayerCarDriverIncidentCount", new VarItem("PlayerCarDriverIncidentCount", 2, 1, false, "Teams current drivers incident count for this session", "") },
            { "PlayerCarDryTireSetLimit", new VarItem("PlayerCarDryTireSetLimit", 2, 1, false, "Players dry tire set limit", "") },
            { "PlayerCarIdx", new VarItem("PlayerCarIdx", 2, 1, false, "Players carIdx", "") },
            { "PlayerCarInPitStall", new VarItem("PlayerCarInPitStall", 1, 1, false, "Players car is properly in their pitstall", "") },
            { "PlayerCarMyIncidentCount", new VarItem("PlayerCarMyIncidentCount", 2, 1, false, "Players own incident count for this session", "") },
            { "PlayerCarPitSvStatus", new VarItem("PlayerCarPitSvStatus", 2, 1, false, "Players car pit service status bits", "irsdk_PitSvStatus") },
            { "PlayerCarPosition", new VarItem("PlayerCarPosition", 2, 1, false, "Players position in race", "") },
            { "PlayerCarPowerAdjust", new VarItem("PlayerCarPowerAdjust", 4, 1, false, "Players power adjust", "%") },
            { "PlayerCarSLBlinkRPM", new VarItem("PlayerCarSLBlinkRPM", 4, 1, false, "Shift light blink rpm", "revs/min") },
            { "PlayerCarSLFirstRPM", new VarItem("PlayerCarSLFirstRPM", 4, 1, false, "Shift light first light rpm", "revs/min") },
            { "PlayerCarSLLastRPM", new VarItem("PlayerCarSLLastRPM", 4, 1, false, "Shift light last light rpm", "revs/min") },
            { "PlayerCarSLShiftRPM", new VarItem("PlayerCarSLShiftRPM", 4, 1, false, "Shift light shift rpm", "revs/min") },
            { "PlayerCarTeamIncidentCount", new VarItem("PlayerCarTeamIncidentCount", 2, 1, false, "Players team incident count for this session", "") },
            { "PlayerCarTowTime", new VarItem("PlayerCarTowTime", 4, 1, false, "Players car is being towed if time is greater than zero", "s") },
            { "PlayerCarWeightPenalty", new VarItem("PlayerCarWeightPenalty", 4, 1, false, "Players weight penalty", "kg") },
            { "PlayerFastRepairsUsed", new VarItem("PlayerFastRepairsUsed", 2, 1, false, "Players car number of fast repairs used", "") },
            { "PlayerTireCompound", new VarItem("PlayerTireCompound", 2, 1, false, "Players car current tire compound", "") },
            { "PlayerTrackSurface", new VarItem("PlayerTrackSurface", 2, 1, false, "Players car track surface type", "irsdk_TrkLoc") },
            { "PlayerTrackSurfaceMaterial", new VarItem("PlayerTrackSurfaceMaterial", 2, 1, false, "Players car track surface material type", "irsdk_TrkSurf") },
            { "Precipitation", new VarItem("Precipitation", 4, 1, false, "Precipitation at start/finish line", "%") },
            { "PushToPass", new VarItem("PushToPass", 1, 1, false, "Push to pass button state", "") },
            { "PushToTalk", new VarItem("PushToTalk", 1, 1, false, "Push to talk button state", "") },
            { "RFSHshockDefl", new VarItem("RFSHshockDefl", 4, 1, false, "RFSH shock deflection", "m") },
            { "RFSHshockDefl_ST", new VarItem("RFSHshockDefl_ST", 4, 6, true, "RFSH shock deflection at 360 Hz", "m") },
            { "RFSHshockVel", new VarItem("RFSHshockVel", 4, 1, false, "RFSH shock velocity", "m/s") },
            { "RFSHshockVel_ST", new VarItem("RFSHshockVel_ST", 4, 6, true, "RFSH shock velocity at 360 Hz", "m/s") },
            { "RFTiresAvailable", new VarItem("RFTiresAvailable", 2, 1, false, "How many right front tires are remaining  255 is unlimited", "") },
            { "RFTiresUsed", new VarItem("RFTiresUsed", 2, 1, false, "How many right front tires used so far", "") },
            { "RFbrakeLinePress", new VarItem("RFbrakeLinePress", 4, 1, false, "RF brake line pressure", "bar") },
            { "RFcoldPressure", new VarItem("RFcoldPressure", 4, 1, false, "RF tire cold pressure  as set in the garage", "kPa") },
            { "RFpressure", new VarItem("RFpressure", 4, 1, false, "RF tire pressure", "kPa") },
            { "RFrideHeight", new VarItem("RFrideHeight", 4, 1, false, "RF ride height", "m") },
            { "RFshockDefl", new VarItem("RFshockDefl", 4, 1, false, "RF shock deflection", "m") },
            { "RFshockDefl_ST", new VarItem("RFshockDefl_ST", 4, 6, true, "RF shock deflection at 360 Hz", "m") },
            { "RFshockVel", new VarItem("RFshockVel", 4, 1, false, "RF shock velocity", "m/s") },
            { "RFshockVel_ST", new VarItem("RFshockVel_ST", 4, 6, true, "RF shock velocity at 360 Hz", "m/s") },
            { "RFspeed", new VarItem("RFspeed", 4, 1, false, "RF wheel speed", "m/s") },
            { "RFtempCL", new VarItem("RFtempCL", 4, 1, false, "RF tire left carcass temperature", "C") },
            { "RFtempCM", new VarItem("RFtempCM", 4, 1, false, "RF tire middle carcass temperature", "C") },
            { "RFtempCR", new VarItem("RFtempCR", 4, 1, false, "RF tire right carcass temperature", "C") },
            { "RFtempL", new VarItem("RFtempL", 4, 1, false, "RF tire left surface temperature", "C") },
            { "RFtempM", new VarItem("RFtempM", 4, 1, false, "RF tire middle surface temperature", "C") },
            { "RFtempR", new VarItem("RFtempR", 4, 1, false, "RF tire right surface temperature", "C") },
            { "RFwearL", new VarItem("RFwearL", 4, 1, false, "RF tire left percent tread remaining", "%") },
            { "RFwearM", new VarItem("RFwearM", 4, 1, false, "RF tire middle percent tread remaining", "%") },
            { "RFwearR", new VarItem("RFwearR", 4, 1, false, "RF tire right percent tread remaining", "%") },
            { "RPM", new VarItem("RPM", 4, 1, false, "Engine rpm", "revs/min") },
            { "RRTiresAvailable", new VarItem("RRTiresAvailable", 2, 1, false, "How many right rear tires are remaining  255 is unlimited", "") },
            { "RRTiresUsed", new VarItem("RRTiresUsed", 2, 1, false, "How many right rear tires used so far", "") },
            { "RRbrakeLinePress", new VarItem("RRbrakeLinePress", 4, 1, false, "RR brake line pressure", "bar") },
            { "RRcoldPressure", new VarItem("RRcoldPressure", 4, 1, false, "RR tire cold pressure  as set in the garage", "kPa") },
            { "RRpressure", new VarItem("RRpressure", 4, 1, false, "RR tire pressure", "kPa") },
            { "RRrideHeight", new VarItem("RRrideHeight", 4, 1, false, "RR ride height", "m") },
            { "RRshockDefl", new VarItem("RRshockDefl", 4, 1, false, "RR shock deflection", "m") },
            { "RRshockDefl_ST", new VarItem("RRshockDefl_ST", 4, 6, true, "RR shock deflection at 360 Hz", "m") },
            { "RRshockVel", new VarItem("RRshockVel", 4, 1, false, "RR shock velocity", "m/s") },
            { "RRshockVel_ST", new VarItem("RRshockVel_ST", 4, 6, true, "RR shock velocity at 360 Hz", "m/s") },
            { "RRspeed", new VarItem("RRspeed", 4, 1, false, "RR wheel speed", "m/s") },
            { "RRtempCL", new VarItem("RRtempCL", 4, 1, false, "RR tire left carcass temperature", "C") },
            { "RRtempCM", new VarItem("RRtempCM", 4, 1, false, "RR tire middle carcass temperature", "C") },
            { "RRtempCR", new VarItem("RRtempCR", 4, 1, false, "RR tire right carcass temperature", "C") },
            { "RRtempL", new VarItem("RRtempL", 4, 1, false, "RR tire left surface temperature", "C") },
            { "RRtempM", new VarItem("RRtempM", 4, 1, false, "RR tire middle surface temperature", "C") },
            { "RRtempR", new VarItem("RRtempR", 4, 1, false, "RR tire right surface temperature", "C") },
            { "RRwearL", new VarItem("RRwearL", 4, 1, false, "RR tire left percent tread remaining", "%") },
            { "RRwearM", new VarItem("RRwearM", 4, 1, false, "RR tire middle percent tread remaining", "%") },
            { "RRwearR", new VarItem("RRwearR", 4, 1, false, "RR tire right percent tread remaining", "%") },
            { "RaceLaps", new VarItem("RaceLaps", 2, 1, false, "Laps completed in race", "") },
            { "RadioTransmitCarIdx", new VarItem("RadioTransmitCarIdx", 2, 1, false, "The car index of the current person speaking on the radio", "") },
            { "RadioTransmitFrequencyIdx", new VarItem("RadioTransmitFrequencyIdx", 2, 1, false, "The frequency index of the current person speaking on the radio", "") },
            { "RadioTransmitRadioIdx", new VarItem("RadioTransmitRadioIdx", 2, 1, false, "The radio index of the current person speaking on the radio", "") },
            { "RearTireSetsAvailable", new VarItem("RearTireSetsAvailable", 2, 1, false, "How many rear tire sets are remaining  255 is unlimited", "") },
            { "RearTireSetsUsed", new VarItem("RearTireSetsUsed", 2, 1, false, "How many rear tire sets used so far", "") },
            { "RelativeHumidity", new VarItem("RelativeHumidity", 4, 1, false, "Relative Humidity at start/finish line", "%") },
            { "ReplayFrameNum", new VarItem("ReplayFrameNum", 2, 1, false, "Integer replay frame number (60 per second)", "") },
            { "ReplayFrameNumEnd", new VarItem("ReplayFrameNumEnd", 2, 1, false, "Integer replay frame number from end of tape", "") },
            { "ReplayPlaySlowMotion", new VarItem("ReplayPlaySlowMotion", 1, 1, false, "0=not slow motion  1=replay is in slow motion", "") },
            { "ReplayPlaySpeed", new VarItem("ReplayPlaySpeed", 2, 1, false, "Replay playback speed", "") },
            { "ReplaySessionNum", new VarItem("ReplaySessionNum", 2, 1, false, "Replay session number", "") },
            { "ReplaySessionTime", new VarItem("ReplaySessionTime", 5, 1, false, "Seconds since replay session start", "s") },
            { "RightTireSetsAvailable", new VarItem("RightTireSetsAvailable", 2, 1, false, "How many right tire sets are remaining  255 is unlimited", "") },
            { "RightTireSetsUsed", new VarItem("RightTireSetsUsed", 2, 1, false, "How many right tire sets used so far", "") },
            { "Roll", new VarItem("Roll", 4, 1, false, "Roll orientation", "rad") },
            { "RollRate", new VarItem("RollRate", 4, 1, false, "Roll rate", "rad/s") },
            { "RollRate_ST", new VarItem("RollRate_ST", 4, 6, true, "Roll rate at 360 Hz", "rad/s") },
            { "SessionFlags", new VarItem("SessionFlags", 3, 1, false, "Session flags", "irsdk_Flags") },
            { "SessionJokerLapsRemain", new VarItem("SessionJokerLapsRemain", 2, 1, false, "Joker laps remaining to be taken", "") },
            { "SessionLapsRemain", new VarItem("SessionLapsRemain", 2, 1, false, "Old laps left till session ends use SessionLapsRemainEx", "") },
            { "SessionLapsRemainEx", new VarItem("SessionLapsRemainEx", 2, 1, false, "New improved laps left till session ends", "") },
            { "SessionLapsTotal", new VarItem("SessionLapsTotal", 2, 1, false, "Total number of laps in session", "") },
            { "SessionNum", new VarItem("SessionNum", 2, 1, false, "Session number", "") },
            { "SessionOnJokerLap", new VarItem("SessionOnJokerLap", 1, 1, false, "Player is currently completing a joker lap", "") },
            { "SessionState", new VarItem("SessionState", 2, 1, false, "Session state", "irsdk_SessionState") },
            { "SessionTick", new VarItem("SessionTick", 2, 1, false, "Current update number", "") },
            { "SessionTime", new VarItem("SessionTime", 5, 1, false, "Seconds since session start", "s") },
            { "SessionTimeOfDay", new VarItem("SessionTimeOfDay", 4, 1, false, "Time of day in seconds", "s") },
            { "SessionTimeRemain", new VarItem("SessionTimeRemain", 5, 1, false, "Seconds left till session ends", "s") },
            { "SessionTimeTotal", new VarItem("SessionTimeTotal", 5, 1, false, "Total number of seconds in session", "s") },
            { "SessionUniqueID", new VarItem("SessionUniqueID", 2, 1, false, "Session ID", "") },
            { "ShiftGrindRPM", new VarItem("ShiftGrindRPM", 4, 1, false, "RPM of shifter grinding noise", "RPM") },
            { "ShiftIndicatorPct", new VarItem("ShiftIndicatorPct", 4, 1, false, "DEPRECATED use DriverCarSLBlinkRPM instead", "%") },
            { "ShiftPowerPct", new VarItem("ShiftPowerPct", 4, 1, false, "Friction torque applied to gears when shifting or grinding", "%") },
            { "Skies", new VarItem("Skies", 2, 1, false, "Skies (0=clear/1=p cloudy/2=m cloudy/3=overcast)", "") },
            { "SolarAltitude", new VarItem("SolarAltitude", 4, 1, false, "Sun angle above horizon in radians", "rad") },
            { "SolarAzimuth", new VarItem("SolarAzimuth", 4, 1, false, "Sun angle clockwise from north in radians", "rad") },
            { "Speed", new VarItem("Speed", 4, 1, false, "GPS vehicle speed", "m/s") },
            { "SteeringWheelAngle", new VarItem("SteeringWheelAngle", 4, 1, false, "Steering wheel angle", "rad") },
            { "SteeringWheelAngleMax", new VarItem("SteeringWheelAngleMax", 4, 1, false, "Steering wheel max angle", "rad") },
            { "SteeringWheelLimiter", new VarItem("SteeringWheelLimiter", 4, 1, false, "Force feedback limiter strength limits impacts and oscillation", "%") },
            { "SteeringWheelMaxForceNm", new VarItem("SteeringWheelMaxForceNm", 4, 1, false, "Value of strength or max force slider in Nm for FFB", "N*m") },
            { "SteeringWheelPctDamper", new VarItem("SteeringWheelPctDamper", 4, 1, false, "Force feedback % max damping", "%") },
            { "SteeringWheelPctIntensity", new VarItem("SteeringWheelPctIntensity", 4, 1, false, "Force feedback % max intensity", "%") },
            { "SteeringWheelPctSmoothing", new VarItem("SteeringWheelPctSmoothing", 4, 1, false, "Force feedback % max smoothing", "%") },
            { "SteeringWheelPctTorque", new VarItem("SteeringWheelPctTorque", 4, 1, false, "Force feedback % max torque on steering shaft unsigned", "%") },
            { "SteeringWheelPctTorqueSign", new VarItem("SteeringWheelPctTorqueSign", 4, 1, false, "Force feedback % max torque on steering shaft signed", "%") },
            { "SteeringWheelPctTorqueSignStops", new VarItem("SteeringWheelPctTorqueSignStops", 4, 1, false, "Force feedback % max torque on steering shaft signed stops", "%") },
            { "SteeringWheelPeakForceNm", new VarItem("SteeringWheelPeakForceNm", 4, 1, false, "Peak torque mapping to direct input units for FFB", "N*m") },
            { "SteeringWheelTorque", new VarItem("SteeringWheelTorque", 4, 1, false, "Output torque on steering shaft", "N*m") },
            { "SteeringWheelTorque_ST", new VarItem("SteeringWheelTorque_ST", 4, 6, true, "Output torque on steering shaft at 360 Hz", "N*m") },
            { "SteeringWheelUseLinear", new VarItem("SteeringWheelUseLinear", 1, 1, false, "True if steering wheel force is using linear mode", "") },
            { "Throttle", new VarItem("Throttle", 4, 1, false, "0=off throttle to 1=full throttle", "%") },
            { "ThrottleRaw", new VarItem("ThrottleRaw", 4, 1, false, "Raw throttle input 0=off throttle to 1=full throttle", "%") },
            { "TireLF_RumblePitch", new VarItem("TireLF_RumblePitch", 4, 1, false, "Players LF Tire Sound rumblestrip pitch", "Hz") },
            { "TireLR_RumblePitch", new VarItem("TireLR_RumblePitch", 4, 1, false, "Players LR Tire Sound rumblestrip pitch", "Hz") },
            { "TireRF_RumblePitch", new VarItem("TireRF_RumblePitch", 4, 1, false, "Players RF Tire Sound rumblestrip pitch", "Hz") },
            { "TireRR_RumblePitch", new VarItem("TireRR_RumblePitch", 4, 1, false, "Players RR Tire Sound rumblestrip pitch", "Hz") },
            { "TireSetsAvailable", new VarItem("TireSetsAvailable", 2, 1, false, "How many tire sets are remaining  255 is unlimited", "") },
            { "TireSetsUsed", new VarItem("TireSetsUsed", 2, 1, false, "How many tire sets used so far", "") },
            { "TrackTemp", new VarItem("TrackTemp", 4, 1, false, "Deprecated  set to TrackTempCrew", "C") },
            { "TrackTempCrew", new VarItem("TrackTempCrew", 4, 1, false, "Temperature of track measured by crew around track", "C") },
            { "TrackWetness", new VarItem("TrackWetness", 2, 1, false, "How wet is the average track surface", "irsdk_TrackWetness") },
            { "VelocityX", new VarItem("VelocityX", 4, 1, false, "X velocity", "m/s") },
            { "VelocityX_ST", new VarItem("VelocityX_ST", 4, 6, true, "X velocity", "m/s at 360 Hz") },
            { "VelocityY", new VarItem("VelocityY", 4, 1, false, "Y velocity", "m/s") },
            { "VelocityY_ST", new VarItem("VelocityY_ST", 4, 6, true, "Y velocity", "m/s at 360 Hz") },
            { "VelocityZ", new VarItem("VelocityZ", 4, 1, false, "Z velocity", "m/s") },
            { "VelocityZ_ST", new VarItem("VelocityZ_ST", 4, 6, true, "Z velocity", "m/s at 360 Hz") },
            { "VertAccel", new VarItem("VertAccel", 4, 1, false, "Vertical acceleration (including gravity)", "m/s^2") },
            { "VertAccel_ST", new VarItem("VertAccel_ST", 4, 6, true, "Vertical acceleration (including gravity) at 360 Hz", "m/s^2") },
            { "VidCapActive", new VarItem("VidCapActive", 1, 1, false, "True if video currently being captured", "") },
            { "VidCapEnabled", new VarItem("VidCapEnabled", 1, 1, false, "True if video capture system is enabled", "") },
            { "Voltage", new VarItem("Voltage", 4, 1, false, "Engine voltage", "V") },
            { "WaterLevel", new VarItem("WaterLevel", 4, 1, false, "Engine coolant level", "l") },
            { "WaterTemp", new VarItem("WaterTemp", 4, 1, false, "Engine coolant temp", "C") },
            { "WeatherDeclaredWet", new VarItem("WeatherDeclaredWet", 1, 1, false, "The steward says rain tires can be used", "") },
            // removed { "WeatherType", new VarItem("WeatherType", 2, 1, false, "Weather dynamics type", "irsdk_WeatherDynamics") },
            // removed { "WeatherVersion", new VarItem("WeatherVersion", 2, 1, false, "Weather version", "irsdk_WeatherVersion") },
            { "WindDir", new VarItem("WindDir", 4, 1, false, "Wind direction at start/finish line", "rad") },
            { "WindVel", new VarItem("WindVel", 4, 1, false, "Wind velocity at start/finish line", "m/s") },
            { "Yaw", new VarItem("Yaw", 4, 1, false, "Yaw orientation", "rad") },
            { "YawNorth", new VarItem("YawNorth", 4, 1, false, "Yaw orientation relative to north", "rad") },
            { "YawRate", new VarItem("YawRate", 4, 1, false, "Yaw rate", "rad/s") },
            { "YawRate_ST", new VarItem("YawRate_ST", 4, 6, true, "Yaw rate at 360 Hz", "rad/s") },
            { "dcAntiRollFront", new VarItem("dcAntiRollFront", 4, 1, false, "In car front anti roll bar adjustment", "") },
            { "dcAntiRollRear", new VarItem("dcAntiRollRear", 4, 1, false, "In car rear anti roll bar adjustment", "") },
            { "dcBrakeBias", new VarItem("dcBrakeBias", 4, 1, false, "In car brake bias adjustment", "") },
            { "dcDashPage", new VarItem("dcDashPage", 4, 1, false, "In car dash display page adjustment", "") },
            { "dcFuelMixture", new VarItem("dcFuelMixture", 4, 1, false, "In car fuel mixture adjustment", "") },
            { "dcHeadlightFlash", new VarItem("dcHeadlightFlash", 1, 1, false, "In car headlight flash control active", "") },
            { "dcLaunchRPM", new VarItem("dcLaunchRPM", 4, 1, false, "In car launch rpm adjustment", "") },
            { "dcPitSpeedLimiterToggle", new VarItem("dcPitSpeedLimiterToggle", 1, 1, false, "In car traction control active", "") },
            { "dcPushToPass", new VarItem("dcPushToPass", 1, 1, false, "In car trigger push to pass", "") },
            { "dcRFBrakeAttachedToggle", new VarItem("dcRFBrakeAttachedToggle", 1, 1, false, "In car Right Front Brake attached(1) or detached(0)", "") },
            { "dcStarter", new VarItem("dcStarter", 1, 1, false, "In car trigger car starter", "") },
            { "dcTearOffVisor", new VarItem("dcTearOffVisor", 1, 1, false, "In car tear off visor film", "") },
            { "dcThrottleShape", new VarItem("dcThrottleShape", 4, 1, false, "In car throttle shape adjustment", "") },
            { "dcToggleWindshieldWipers", new VarItem("dcToggleWindshieldWipers", 1, 1, false, "In car turn wipers on or off", "") },
            { "dcTractionControl", new VarItem("dcTractionControl", 4, 1, false, "In car traction control adjustment", "") },
            { "dcTriggerWindshieldWipers", new VarItem("dcTriggerWindshieldWipers", 1, 1, false, "In car momentarily turn on wipers", "") },
            { "dcWeightJackerRight", new VarItem("dcWeightJackerRight", 4, 1, false, "In car right wedge/weight jacker adjustment", "") },
            { "dpFastRepair", new VarItem("dpFastRepair", 4, 1, false, "Pitstop fast repair set", "") },
            { "dpFuelAddKg", new VarItem("dpFuelAddKg", 4, 1, false, "Pitstop fuel add amount", "kg") },
            { "dpFuelAutoFillActive", new VarItem("dpFuelAutoFillActive", 4, 1, false, "Pitstop auto fill fuel next stop flag", "") },
            { "dpFuelAutoFillEnabled", new VarItem("dpFuelAutoFillEnabled", 4, 1, false, "Pitstop auto fill fuel system enabled", "") },
            { "dpFuelFill", new VarItem("dpFuelFill", 4, 1, false, "Pitstop fuel fill flag", "") },
            { "dpLFTireChange", new VarItem("dpLFTireChange", 4, 1, false, "Pitstop lf tire change request", "") },
            { "dpLFTireColdPress", new VarItem("dpLFTireColdPress", 4, 1, false, "Pitstop lf tire cold pressure adjustment", "Pa") },
            { "dpLRTireChange", new VarItem("dpLRTireChange", 4, 1, false, "Pitstop lr tire change request", "") },
            { "dpLRTireColdPress", new VarItem("dpLRTireColdPress", 4, 1, false, "Pitstop lr tire cold pressure adjustment", "Pa") },
            { "dpRFTireChange", new VarItem("dpRFTireChange", 4, 1, false, "Pitstop rf tire change request", "") },
            { "dpRFTireColdPress", new VarItem("dpRFTireColdPress", 4, 1, false, "Pitstop rf cold tire pressure adjustment", "Pa") },
            { "dpRRTireChange", new VarItem("dpRRTireChange", 4, 1, false, "Pitstop rr tire change request", "") },
            { "dpRRTireColdPress", new VarItem("dpRRTireColdPress", 4, 1, false, "Pitstop rr cold tire pressure adjustment", "Pa") },
            { "dpTireChange", new VarItem("dpTireChange", 4, 1, false, "Pitstop all tire change request", "") },
            { "dpWindshieldTearoff", new VarItem("dpWindshieldTearoff", 4, 1, false, "Pitstop windshield tearoff", "") },
            { "dpWingFront", new VarItem("dpWingFront", 4, 1, false, "Pitstop front wing adjustment", "") },
            { "dpWingRear", new VarItem("dpWingRear", 4, 1, false, "Pitstop rear wing adjustment", "") }
        };
    }
}



