/**
 * Copyright (C) 2024-2026 Scott Velez
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
**/

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;

namespace SVappsLAB.iRacingTelemetrySDK
{
    /// <summary>
    /// Represents a telemetry client for iRacing.
    /// </summary>
    /// <typeparam name="T">The 'TelemetryData' type generated by the 'RequiredTelemetryVars' attribute</typeparam>
    public interface ITelemetryClient<T> : IAsyncDisposable where T : struct
    {
        /// <summary>
        /// Gets an async stream for connection state changes.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <strong>Cancellation:</strong> Use <c>.WithCancellation(cancellationToken)</c> to enable
        /// cooperative cancellation when consuming this stream.
        /// </para>
        /// <para>
        /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
        /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
        /// and may cause undefined behavior. For multiple subscribers, use the <c>SubscribeToAllStreams</c> extension
        /// method or create separate subscriptions.
        /// </para>
        /// </remarks>
        /// <example>
        /// <code>
        /// await foreach (var state in client.ConnectStates.WithCancellation(ct))
        /// {
        ///     // Handle connection state change (Connected/Disconnected)
        /// }
        /// </code>
        /// </example>
        IAsyncEnumerable<ConnectState> ConnectStates { get; }

        /// <summary>
        /// Gets an async stream for error notifications.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <strong>Cancellation:</strong> Use <c>.WithCancellation(cancellationToken)</c> to enable
        /// cooperative cancellation when consuming this stream.
        /// </para>
        /// <para>
        /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
        /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
        /// and may cause undefined behavior. For multiple subscribers, use the <c>SubscribeToAllStreams</c> extension
        /// method or create separate subscriptions.
        /// </para>
        /// </remarks>
        /// <example>
        /// <code>
        /// await foreach (var error in client.Errors.WithCancellation(ct))
        /// {
        ///     // Handle error exception
        /// }
        /// </code>
        /// </example>
        IAsyncEnumerable<Exception> Errors { get; }

        /// <summary>
        /// Gets an async stream for raw session info updates in YAML format.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <strong>Cancellation:</strong> Use <c>.WithCancellation(cancellationToken)</c> to enable
        /// cooperative cancellation when consuming this stream.
        /// </para>
        /// <para>
        /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
        /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
        /// and may cause undefined behavior. For multiple subscribers, use the <c>SubscribeToAllStreams</c> extension
        /// method or create separate subscriptions.
        /// </para>
        /// </remarks>
        /// <example>
        /// <code>
        /// await foreach (var rawYaml in client.SessionDataYaml.WithCancellation(ct))
        /// {
        ///     // Process raw YAML session data
        /// }
        /// </code>
        /// </example>
        IAsyncEnumerable<string> SessionDataYaml { get; }

        /// <summary>
        /// Gets an async stream for parsed session info updates.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <strong>Cancellation:</strong> Use <c>.WithCancellation(cancellationToken)</c> to enable
        /// cooperative cancellation when consuming this stream.
        /// </para>
        /// <para>
        /// <strong>Channel Behavior:</strong> Uses a 60-sample ring buffer with FIFO (First-In-First-Out)
        /// semantics and destructive reads. Session info updates are infrequent (typically only at
        /// session state changes), but if your application cannot consume updates fast enough and the
        /// buffer fills, the oldest unread updates are automatically discarded to make room for new data.
        /// </para>
        /// <para>
        /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
        /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
        /// and may cause undefined behavior. For multiple subscribers, use the <c>SubscribeToAllStreams</c> extension
        /// method or create separate subscriptions.
        /// </para>
        /// </remarks>
        /// <example>
        /// <code>
        /// await foreach (var sessionInfo in client.SessionData.WithCancellation(ct))
        /// {
        ///     // Process parsed session information
        /// }
        /// </code>
        /// </example>
        IAsyncEnumerable<TelemetrySessionInfo> SessionData { get; }

        /// <summary>
        /// Gets an async stream for telemetry data updates at 60Hz.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <strong>Cancellation:</strong> Use <c>.WithCancellation(cancellationToken)</c> to enable
        /// cooperative cancellation when consuming this stream.
        /// </para>
        /// <para>
        /// <strong>Channel Behavior:</strong> Uses a 60-sample ring buffer with FIFO (First-In-First-Out)
        /// semantics and destructive reads. At iRacing's 60Hz update rate, this buffer provides up to
        /// 1 second of telemetry data buffering. If your application cannot consume samples fast enough
        /// and the buffer fills to capacity, the oldest unread samples are automatically discarded to
        /// make room for new incoming data. This 'drop-oldest' strategy ensures the SDK never blocks
        /// iRacing's data stream and prioritizes delivering the most recent telemetry to your application.
        /// </para>
        /// <para>
        /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
        /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
        /// and may cause undefined behavior. For multiple subscribers, use the <c>SubscribeToAllStreams</c> extension
        /// method or create separate subscriptions.
        /// </para>
        /// </remarks>
        /// <example>
        /// <code>
        /// await foreach (var telemetry in client.TelemetryData.WithCancellation(ct))
        /// {
        ///     // Process telemetry data (Speed, RPM, etc.)
        /// }
        /// </code>
        /// </example>
        IAsyncEnumerable<T> TelemetryData { get; }

        /// <summary>
        /// Retrieves the telemetry variables available for the current session.
        /// </summary>
        /// <returns>
        /// A read-only list of telemetry variables. Returns an empty list if called before
        /// the data provider has been initialized (typically during or after the first
        /// Monitor() call in live mode, or immediately after construction for IBT mode).
        /// </returns>
        /// <remarks>
        /// <para><strong>Initialization Timing:</strong> In live mode, variable headers become
        /// available only after iRacing is running and the first data update occurs. In IBT mode,
        /// they're available immediately after construction.</para>
        /// <para><strong>Thread Safety:</strong> This method is thread-safe and can be called
        /// concurrently with Monitor(), though results may vary depending on initialization state.</para>
        /// </remarks>
        /// <exception cref="ObjectDisposedException">Thrown if the client has been disposed.</exception>
        IReadOnlyList<TelemetryVariable> GetTelemetryVariables();


        /// <summary>
        /// Monitors the telemetry data and writes data to streams when new data is available.
        /// </summary>
        /// <param name="ct">The cancellation token to cancel the monitoring operation.</param>
        /// <returns>
        /// A task that represents the asynchronous monitoring operation.
        /// The result is the number of telemetry data records processed during the monitoring session.
        /// For live sessions, this represents the count of telemetry updates received.
        /// For IBT playback, this represents the total number of records processed from the file.
        /// </returns>
        /// <remarks>
        /// <para><strong>IMPORTANT:</strong> This method can only be called ONCE per TelemetryClient instance.
        /// After Monitor() completes (via cancellation or IBT file EOF), the client cannot be restarted.
        /// Create a new client instance for subsequent monitoring sessions.</para>
        /// <para><strong>Concurrent Calls:</strong> Calling Monitor() while already running will throw
        /// InvalidOperationException. Ensure the previous Monitor() call has completed before starting
        /// a new client instance.</para>
        /// </remarks>
        Task<int> Monitor(CancellationToken ct);

        /// <summary>
        /// Gets a value indicating whether the client is connected to the telemetry source.
        /// </summary>
        /// <value>
        /// <c>true</c> if connected to iRacing (live mode) or an IBT file is open; otherwise <c>false</c>.
        /// </value>
        /// <remarks>
        /// This property is safe to call from any thread and will return <c>false</c> if the client
        /// has been disposed or is not yet initialized.
        /// </remarks>
        bool IsConnected { get; }

        /// <summary>
        /// Pauses stream data writing. Processing continues, but stream writes are suppressed.
        /// </summary>
        void Pause();

        /// <summary>
        /// Resumes stream data writing.
        /// </summary>
        void Resume();

        /// <summary>
        /// Gets a value indicating whether stream writes are currently paused.
        /// </summary>
        bool IsPaused { get; }
    }
}

