/**
 * Copyright (C) 2024-2026 Scott Velez
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
**/

using SVappsLAB.iRacingTelemetrySDK.SimControl;

namespace SVappsLAB.iRacingTelemetrySDK;

/// <summary>
/// Represents a telemetry client for iRacing.
/// </summary>
/// <typeparam name="T">The 'TelemetryData' type generated by the 'RequiredTelemetryVars' attribute</typeparam>
public interface ITelemetryClient<T> : IAsyncDisposable where T : struct
{
    /// <summary>
    /// Gets an async stream for connection state changes.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>Lifetime:</strong> This stream completes when <see cref="Monitor(CancellationToken)"/> completes.
    /// Use <c>.WithCancellation(cancellationToken)</c> only when this specific consumer should stop
    /// before monitoring stops.
    /// </para>
    /// <para>
    /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
    /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
    /// and may cause undefined behavior. For callback-based consumption, use the
    /// <see cref="Monitor(TelemetryHandlers{T}, CancellationToken)"/> overload.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// await foreach (var state in client.ConnectStates)
    /// {
    ///     // Handle connection state change (Connected/Disconnected)
    /// }
    /// </code>
    /// </example>
    IAsyncEnumerable<ConnectState> ConnectStates { get; }

    /// <summary>
    /// Gets an async stream for error notifications.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>Lifetime:</strong> This stream completes when <see cref="Monitor(CancellationToken)"/> completes.
    /// Use <c>.WithCancellation(cancellationToken)</c> only when this specific consumer should stop
    /// before monitoring stops.
    /// </para>
    /// <para>
    /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
    /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
    /// and may cause undefined behavior. For callback-based consumption, use the
    /// <see cref="Monitor(TelemetryHandlers{T}, CancellationToken)"/> overload.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// await foreach (var error in client.Errors)
    /// {
    ///     // Handle error exception
    /// }
    /// </code>
    /// </example>
    IAsyncEnumerable<Exception> Errors { get; }

    /// <summary>
    /// Gets an async stream for raw session info updates in YAML format.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>Lifetime:</strong> This stream completes when <see cref="Monitor(CancellationToken)"/> completes.
    /// Use <c>.WithCancellation(cancellationToken)</c> only when this specific consumer should stop
    /// before monitoring stops.
    /// </para>
    /// <para>
    /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
    /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
    /// and may cause undefined behavior. For callback-based consumption, use the
    /// <see cref="Monitor(TelemetryHandlers{T}, CancellationToken)"/> overload.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// await foreach (var rawYaml in client.SessionDataYaml)
    /// {
    ///     // Process raw YAML session data
    /// }
    /// </code>
    /// </example>
    IAsyncEnumerable<string> SessionDataYaml { get; }

    /// <summary>
    /// Gets an async stream for parsed session info updates.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>Lifetime:</strong> This stream completes when <see cref="Monitor(CancellationToken)"/> completes.
    /// Use <c>.WithCancellation(cancellationToken)</c> only when this specific consumer should stop
    /// before monitoring stops.
    /// </para>
    /// <para>
    /// <strong>Channel Behavior:</strong> Uses a 60-sample ring buffer with FIFO (First-In-First-Out)
    /// semantics and destructive reads. Session info updates are infrequent (typically only at
    /// session state changes), but if your application cannot consume updates fast enough and the
    /// buffer fills, the oldest unread updates are automatically discarded to make room for new data.
    /// </para>
    /// <para>
    /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
    /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
    /// and may cause undefined behavior. For callback-based consumption, use the
    /// <see cref="Monitor(TelemetryHandlers{T}, CancellationToken)"/> overload.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// await foreach (var sessionInfo in client.SessionData)
    /// {
    ///     // Process parsed session information
    /// }
    /// </code>
    /// </example>
    IAsyncEnumerable<TelemetrySessionInfo> SessionData { get; }

    /// <summary>
    /// Gets an async stream for telemetry data updates at 60Hz.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>Lifetime:</strong> This stream completes when <see cref="Monitor(CancellationToken)"/> completes.
    /// Use <c>.WithCancellation(cancellationToken)</c> only when this specific consumer should stop
    /// before monitoring stops.
    /// </para>
    /// <para>
    /// <strong>Channel Behavior:</strong> Uses a 60-sample ring buffer with FIFO (First-In-First-Out)
    /// semantics and destructive reads. At iRacing's 60Hz update rate, this buffer provides up to
    /// 1 second of telemetry data buffering. If your application cannot consume samples fast enough
    /// and the buffer fills to capacity, the oldest unread samples are automatically discarded to
    /// make room for new incoming data. This 'drop-oldest' strategy ensures the SDK never blocks
    /// iRacing's data stream and prioritizes delivering the most recent telemetry to your application.
    /// </para>
    /// <para>
    /// <strong>Single Reader Limitation:</strong> This async stream is optimized for single concurrent reader.
    /// Attempting multiple concurrent enumerations (e.g., multiple <c>await foreach</c> loops) is not supported
    /// and may cause undefined behavior. For callback-based consumption, use the
    /// <see cref="Monitor(TelemetryHandlers{T}, CancellationToken)"/> overload.
    /// </para>
    /// <para>
    /// <strong>Not available in Synchronous delivery mode:</strong> when the client is created with
    /// <see cref="ClientOptions.DeliveryMode"/> set to <see cref="TelemetryDeliveryMode.Synchronous"/>, samples
    /// are delivered directly to <see cref="TelemetryHandlers{T}.OnTelemetryUpdate"/> instead of being queued on
    /// this stream. Accessing this property in that mode throws <see cref="InvalidOperationException"/>.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// await foreach (var telemetry in client.TelemetryData)
    /// {
    ///     // Process telemetry data (Speed, RPM, etc.)
    /// }
    /// </code>
    /// </example>
    IAsyncEnumerable<T> TelemetryData { get; }

    /// <summary>
    /// Retrieves the telemetry variables available for the current session.
    /// </summary>
    /// <returns>
    /// A read-only list of telemetry variables. Returns an empty list if called before
    /// the data provider has been initialized (typically during or after the first
    /// Monitor() call, for both live and IBT mode).
    /// </returns>
    /// <remarks>
    /// <para><strong>Initialization Timing:</strong> In live mode, variable headers become
    /// available only after iRacing is running and the first data update occurs. In IBT mode,
    /// they become available once <c>Monitor()</c> opens the file</para>
    /// <para><strong>Thread Safety:</strong> This method is thread-safe and can be called
    /// concurrently with Monitor(), though results may vary depending on initialization state.</para>
    /// </remarks>
    /// <exception cref="ObjectDisposedException">Thrown if the client has been disposed.</exception>
    IReadOnlyList<TelemetryVariable> GetTelemetryVariables();

    /// <summary>
    /// Gets the current value of a telemetry variable by name.
    /// </summary>
    /// <param name="varName">
    /// The iRacing telemetry variable name (e.g. "Speed", "RPM", "CarIdxTrackSurface"). Names are matched
    /// case-insensitively and are not limited to the variables declared on <typeparamref name="T"/> - any
    /// variable reported by <see cref="GetTelemetryVariables"/> can be looked up this way.
    /// </param>
    /// <returns>
    /// The current value, boxed as a scalar (e.g. a <see cref="float"/>) or an array (e.g. <c>float[]</c>)
    /// depending on the variable, or <see langword="null"/> if <paramref name="varName"/> is not a known
    /// variable or telemetry data is not yet available.
    /// </returns>
    /// <remarks>
    /// <para>
    /// Use this for scenarios where the set of variables is only known at runtime - for example, a dashboard
    /// that lets end users pick which telemetry values to display, or an integration (such as a game engine)
    /// that prefers a dynamic, string-keyed lookup over a compile-time generated struct. See
    /// <see cref="DynamicTelemetryData"/> for a <typeparamref name="T"/> placeholder that avoids the need for
    /// a <c>RequiredTelemetryVars</c>-annotated struct entirely.
    /// </para>
    /// <para>
    /// Prefer the strongly-typed <typeparamref name="T"/> for variables known at compile time - it is
    /// allocation-free.
    /// </para>
    /// <para>
    /// <strong>Only usable in <see cref="TelemetryDeliveryMode.Synchronous"/> mode.</strong> The SDK operates
    /// in exactly one of two modes, chosen when the client is created via <see cref="ClientOptions.DeliveryMode"/>,
    /// and does not allow mixing them: in the default <see cref="TelemetryDeliveryMode.Async"/> mode, production
    /// and consumption run on independent tasks, so there would be no way to guarantee this method reflects the
    /// same record as the <typeparamref name="T"/> sample passed to
    /// <see cref="TelemetryHandlers{T}.OnTelemetryUpdate"/> - calling it in that mode throws
    /// <see cref="InvalidOperationException"/>. In <see cref="TelemetryDeliveryMode.Synchronous"/> mode, this
    /// method is guaranteed to reflect exactly the sample passed to the currently-running handler, because the
    /// next record isn't read until the handler returns.
    /// </para>
    /// </remarks>
    /// <exception cref="ObjectDisposedException">Thrown if the client has been disposed.</exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown if the client was created with <see cref="ClientOptions.DeliveryMode"/> set to
    /// <see cref="TelemetryDeliveryMode.Async"/>.
    /// </exception>
    object? GetValue(string varName);

    /// <summary>
    /// Monitors the telemetry data and writes data to streams when new data is available.
    /// </summary>
    /// <param name="ct">The cancellation token to cancel the monitoring operation.</param>
    /// <returns>
    /// A task that represents the asynchronous monitoring operation.
    /// The result is the number of telemetry data records processed during the monitoring session.
    /// For live sessions, this represents the count of telemetry updates received.
    /// For IBT playback, this represents the total number of records processed from the file.
    /// </returns>
    /// <remarks>
    /// <para><strong>IMPORTANT:</strong> This method can only be called ONCE per TelemetryClient instance.
    /// After Monitor() completes (via cancellation or IBT file EOF), the client cannot be restarted.
    /// Create a new client instance for subsequent monitoring sessions.</para>
    /// <para><strong>Concurrent Calls:</strong> Calling Monitor() while already running will throw
    /// InvalidOperationException. Ensure the previous Monitor() call has completed before starting
    /// a new client instance.</para>
    /// <para><strong>Synchronous delivery mode:</strong> this overload supplies no
    /// <see cref="TelemetryHandlers{T}.OnTelemetryUpdate"/> handler, so it is incompatible with
    /// <see cref="TelemetryDeliveryMode.Synchronous"/> - use
    /// <see cref="Monitor(TelemetryHandlers{T}, CancellationToken)"/> instead.</para>
    /// </remarks>
    /// <exception cref="InvalidOperationException">
    /// Thrown immediately if the client was created with <see cref="TelemetryDeliveryMode.Synchronous"/>.
    /// </exception>
    Task<int> Monitor(CancellationToken ct);

    /// <summary>
    /// Monitors telemetry data and invokes callback handlers for selected streams.
    /// </summary>
    /// <param name="handlers">The callback handlers to invoke while monitoring.</param>
    /// <param name="ct">The cancellation token to stop the monitoring operation.</param>
    /// <returns>
    /// A task that represents the asynchronous monitoring operation.
    /// The result is the number of telemetry data records processed during the monitoring session.
    /// </returns>
    /// <remarks>
    /// <para>
    /// This overload is the simplest way to consume telemetry. It starts stream consumption,
    /// starts monitoring, and returns when monitoring ends. Cancelling <paramref name="ct"/>
    /// stops monitoring and returns normally after handlers finish.
    /// </para>
    /// <para>
    /// Handler exceptions fault this method directly - this holds for both
    /// <see cref="TelemetryDeliveryMode.Async"/> and <see cref="TelemetryDeliveryMode.Synchronous"/>. SDK
    /// processing errors are delivered to <see cref="TelemetryHandlers{T}.OnError"/> when that handler is
    /// provided; handler exceptions are never routed there.
    /// </para>
    /// <para>
    /// Handlers are awaited sequentially per stream. Keep handlers fast, especially telemetry
    /// handlers that may run at 60Hz.
    /// </para>
    /// <para>
    /// <strong>Synchronous delivery mode:</strong> requires <see cref="TelemetryHandlers{T}.OnTelemetryUpdate"/>
    /// to be set; otherwise telemetry samples would be silently discarded.
    /// </para>
    /// </remarks>
    /// <exception cref="InvalidOperationException">
    /// Thrown immediately if the client was created with <see cref="TelemetryDeliveryMode.Synchronous"/> and
    /// <paramref name="handlers"/> does not set <see cref="TelemetryHandlers{T}.OnTelemetryUpdate"/>.
    /// </exception>
    Task<int> Monitor(TelemetryHandlers<T> handlers, CancellationToken ct);

    /// <summary>
    /// Gets a value indicating whether the client is connected to the telemetry source.
    /// </summary>
    /// <value>
    /// <c>true</c> if connected to iRacing (live mode) or an IBT file is open; otherwise <c>false</c>.
    /// </value>
    /// <remarks>
    /// This property is safe to call from any thread and will return <c>false</c> if the client
    /// has been disposed or is not yet initialized.
    /// </remarks>
    bool IsConnected { get; }

    /// <summary>
    /// Pauses stream data writing. Processing continues, but stream writes are suppressed.
    /// </summary>
    /// <remarks>
    /// <para><strong>Thread Safety:</strong> This method is thread-safe and can be called from any thread.</para>
    /// <para><strong>Idempotency:</strong> Safe to call multiple times. Calling Pause() when already paused has no effect.</para>
    /// <para><strong>Eventual Consistency:</strong> Changes are not immediate. A few telemetry samples may be written
    /// to streams before the pause takes effect</para>
    /// </remarks>
    void Pause();

    /// <summary>
    /// Resumes stream data writing.
    /// </summary>
    /// <remarks>
    /// <para><strong>Thread Safety:</strong> This method is thread-safe and can be called from any thread.</para>
    /// <para><strong>Idempotency:</strong> Safe to call multiple times. Calling Resume() when not paused has no effect.</para>
    /// <para><strong>Eventual Consistency:</strong> Changes are not immediate. A few telemetry samples may be suppressed
    /// before the resume takes effect.</para>
    /// </remarks>
    void Resume();

    /// <summary>
    /// Gets a value indicating whether stream writes are currently paused.
    /// </summary>
    bool IsPaused { get; }

    /// <summary>
    /// Gets the remote-control interface for the simulator (cameras, replay, pit service, chat, ...).
    /// </summary>
    ISimController SimControl { get; }
}
