name: buildAndtest
on:
  push:

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Sdk
    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: restore dependencies
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore -c release
      - name: unit tests
        run: dotnet test --no-restore -c release --filter UnitTests
    # can't run IBT tests with github runers - because we don't have
    # access to memory mapped files on the host
    # - name: ibt tests
    #   run: dotnet test --no-restore -c release --filter IBT_Tests
