name: publish to nuget
on:
  workflow_dispatch:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Sdk
    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: restore dependencies
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore -c release
      - name: pack
        # for whatever reason, build defaults to 'Release' with capital 'R' but pack defaults to 'release' with lowercase 'r
        # explicitly use 'Release' for enable pack to find the directory
        run: dotnet pack --no-restore -c Release -o .\artifacts SVappsLAB.iRacingTelemetrySDK
      - name: publishPackage
        run: dotnet nuget push .\artifacts\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
